//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Handler.rc
//
#define IDR_MANIFEST                    1
#define ID_ABOUT                        100
#define ID_ADMIN                        101
#define IDD_DIALOG_ULD_STACKER_STATUS   101
#define ID_ALARM                        102
#define ID_BASIC                        103
#define ID_EMPTY                        104
#define ID_EXIT                         105
#define ID_FILE_EDITOR                  106
#define ID_IO                           107
#define ID_LEVEL                        108
#define ID_LIST                         109
#define ID_LIST_DATAVIEW                110
#define ID_LIST_OPER                    111
#define ID_LIST_STEP                    112
#define ID_LOCK                         113
#define ID_MAIN                         114
#define ID_MOT_BUFFER                   115
#define ID_MOT_SHIFTER                  116
#define ID_MOT_SPEED                    117
#define ID_MOT_TEACH                    118
#define ID_MOT_TOTAL                    119
#define ID_MOTOR                        120
#define ID_RESET                        121
#define ID_SAVE                         122
#define ID_SET_INTERFACE                123
#define ID_SET_MAINTENANCE              124
#define ID_SET_TESTREFERENCE            125
#define ID_SETTING                      126
#define ID_WAIT                         127
#define IDB_BIG3                        128
#define IDB_CLOCKST_BIG                 129
#define IDB_CLOCKST_PANE                130
#define IDB_CLOCKST_SMALL               131
#define IDB_DATEPICKER_BUTTON           132
#define IDB_DIGITSTEX_BBDISABLE         133
#define IDB_DIGITSTEX_BBLACK            134
#define IDB_DIGITSTEX_BBLUE             135
#define IDB_DIGITSTEX_BCYAN             136
#define IDB_DIGITSTEX_BDISABLE          137
#define IDB_DIGITSTEX_BGREEN            138
#define IDB_DIGITSTEX_BLACK             139
#define IDB_DIGITSTEX_BRED              140
#define IDB_DIGITSTEX_BYELLOW           141
#define IDB_DIGITSTEX_CYAN              142
#define IDB_DIGITSTEX_DISABLE           143
#define IDB_DIGITSTEX_GREEN             144
#define IDB_DIGITSTEX_RED               145
#define IDB_DIGITSTEX_SBDISABLE         146
#define IDB_DIGITSTEX_YELLOW            147
#define IDB_GREENBUTTON                 148
#define IDB_INITIAL_STR_1               149
#define IDB_INITIAL_STR_2               150
#define IDB_MATRIXLARGE                 151
#define IDB_MATRIXSMALL                 152
#define IDB_MATRIXTINY                  153
#define IDB_REDBUTTON                   154
#define IDB_TOOLBAR_DRAW                155
#define IDB_TOOLBAR_DRAW_DISABLED       156
#define IDB_TOOLBAR_DRAW_HOT            157
#define IDC_BMP_VIEW                    158
#define IDC_BTN_ADD_4200                159
#define IDC_BTN_ADD_4201                160
#define IDC_BTN_ADD_4202                161
#define IDC_BTN_ADD_FAIL                162
#define IDC_BTN_ALARM_RESET_1           163
#define IDC_BTN_RFID_WRITE              163
#define IDC_BTN_ALARM_RESET_2           164
#define IDC_BTN_ALARM_RESET_3           165
#define IDC_BTN_ALARM_RESET_4           166
#define IDC_BTN_ALARM_RESET_5           167
#define IDC_BTN_APCT_BLOT_TEST          168
#define IDC_BTN_APCT_SOCKET_INFO_TEST   169
#define IDC_BTN_APPLY                   170
#define IDC_BTN_BACK_SITE               171
#define IDC_BTN_BARCODE_TEST            172
#define IDC_BTN_BASIC_APPLY             173
#define IDC_BTN_BASIC_CANCEL            174
#define IDC_BTN_BASIC_CANCLE            175
#define IDC_BTN_BASIC_RELOAD            176
#define IDC_BTN_BC_DN                   177
#define IDC_BTN_BC_UP                   178
#define IDC_BTN_BOARD_0                 179
#define IDC_BTN_BOARD_1                 180
#define IDC_BTN_BOARD_2                 181
#define IDC_BTN_BOARD_3                 182
#define IDC_BTN_BOARD_4                 183
#define IDC_BTN_BOARD_5                 184
#define IDC_BTN_BOARD_6                 185
#define IDC_BTN_BOARD_7                 186
#define IDC_BTN_BOARD_8                 187
#define IDC_BTN_BOARD_9                 188
#define IDC_BTN_BOARD_A                 189
#define IDC_BTN_BOARD_ADD               190
#define IDC_BTN_BOARD_B                 191
#define IDC_BTN_BOARD_BACK              192
#define IDC_BTN_BOARD_C                 193
#define IDC_BTN_BOARD_D                 194
#define IDC_BTN_BOARD_DEL               195
#define IDC_BTN_BOARD_DIV               196
#define IDC_BTN_BOARD_DOLLAR            197
#define IDC_BTN_BOARD_DOT               198
#define IDC_BTN_BOARD_E                 199
#define IDC_BTN_BOARD_F                 200
#define IDC_BTN_BOARD_G                 201
#define IDC_BTN_BOARD_H                 202
#define IDC_BTN_BOARD_I                 203
#define IDC_BTN_BOARD_J                 204
#define IDC_BTN_BOARD_K                 205
#define IDC_BTN_BOARD_L                 206
#define IDC_BTN_BOARD_LBRACE_B          207
#define IDC_BTN_BOARD_LBRACE_S          208
#define IDC_BTN_BOARD_LINE              209
#define IDC_BTN_BOARD_M                 210
#define IDC_BTN_BOARD_N                 211
#define IDC_BTN_BOARD_O                 212
#define IDC_BTN_BOARD_P                 213
#define IDC_BTN_BOARD_Q                 214
#define IDC_BTN_BOARD_R                 215
#define IDC_BTN_BOARD_RBRACE_B          216
#define IDC_BTN_BOARD_RBRACE_S          217
#define IDC_BTN_BOARD_S                 218
#define IDC_BTN_BOARD_SHARP             219
#define IDC_BTN_BOARD_T                 220
#define IDC_BTN_BOARD_U                 221
#define IDC_BTN_BOARD_V                 222
#define IDC_BTN_BOARD_W                 223
#define IDC_BTN_BOARD_X                 224
#define IDC_BTN_BOARD_Y                 225
#define IDC_BTN_BOARD_Z                 226
#define IDC_BTN_BUFFER_IN_TEST          227
#define IDC_BTN_BUFFER_READY_TEST       228
#define IDC_BTN_BUFFER_SEARCH           229
#define IDC_BTN_BUFFERDB_DELETE         230
#define IDC_BTN_SCARP_SEARCH            230
#define IDC_BTN_BUZZER_OFF              231
#define IDC_BTN_SCRAPDB_DELETE          231
#define IDC_BTN_CONNECT_APCT            232
#define IDC_BTN_CONNECT_BPC             233
#define IDC_BTN_CONNECT_ECSERVER        234
#define IDC_BTN_CONNECT_ECSERVER2       235
#define IDC_BTN_CONNECT_LOT_DISPLAY_ECSERVER 235
#define IDC_BTN_CONNECT_NEXT            236
#define IDC_BTN_CONNECT_ALARM_ECSERVER  236
#define IDC_BTN_CONNECT_NMACHINE        237
#define IDC_BTN_DATA_BACKUP             238
#define IDC_BTN_DAY_NEXT                239
#define IDC_BTN_DAY_PREV                240
#define IDC_BTN_DAY_TODAY               241
#define IDC_BTN_DELETE                  242
#define IDC_BTN_DELETE_ALL_STKACER      242
#define IDC_BTN_DOOR_OPEN               243
#define IDC_BTN_DRAW_SITE               244
#define IDC_BTN_BCR_RETRY               244
#define IDC_BTN_DELETE_SELECT_STACKER   244
#define IDC_BTN_DVC_CREATE              245
#define IDC_BTN_DVC_DELETE              246
#define IDC_BTN_EJECTOR_DN              247
#define IDC_BTN_EJECTOR_UP              248
#define IDC_BTN_ELECTROSTATIC_TEST      249
#define IDC_BTN_EMG                     250
#define IDC_BTN_DC_CANCEL               250
#define IDC_BTN_EMO_STOP                251
#define IDC_BTN_DC_OK                   251
#define IDC_BTN_END_TIME                252
#define IDC_BTN_EXIT                    253
#define IDC_BTN_FILE_EDITOR             254
#define IDC_BTN_FRONT_BUFFER            255
#define IDC_BTN_FTP_CONNECT_TEST        256
#define IDC_BTN_FTP_TEST                257
#define IDC_BTN_FTPID_SAVE              258
#define IDC_BTN_FTPIP_SAVE              259
#define IDC_BTN_FTPPASSWORD_SAVE        260
#define IDC_BTN_FTPPORT_SAVE            261
#define IDC_BTN_GROUND_TEST             262
#define IDC_BTN_HOME                    263
#define IDC_BTN_HOMING_1                264
#define IDC_BTN_HOMING_2                265
#define IDC_BTN_HOMING_3                266
#define IDC_BTN_HOMING_4                267
#define IDC_BTN_HOMING_5                268
#define IDC_BTN_I_GRID                  269
#define IDC_BTN_I_GRID2                 270
#define IDC_BTN_I_TEXT                  271
#define IDC_BTN_I_TEXT2                 272
#define IDC_BTN_INIT_RETRY              273
#define IDC_BTN_INIT_SKIP               274
#define IDC_BTN_IO                      275
#define IDC_BTN_IO_E_STOP               276
#define IDC_BTN_IO_MOVE_1               277
#define IDC_BTN_IO_MOVE_10              278
#define IDC_BTN_IO_MOVE_11              279
#define IDC_BTN_IO_MOVE_12              280
#define IDC_BTN_IO_MOVE_2               281
#define IDC_BTN_IO_MOVE_3               282
#define IDC_BTN_IO_MOVE_4               283
#define IDC_BTN_IO_MOVE_5               284
#define IDC_BTN_IO_MOVE_6               285
#define IDC_BTN_IO_MOVE_7               286
#define IDC_BTN_IO_MOVE_8               287
#define IDC_BTN_IO_MOVE_9               288
#define IDC_BTN_IO_OPEN                 289
#define IDC_BTN_IO_PART_OPEN            290
#define IDC_BTN_IO_PART_SAVE            291
#define IDC_BTN_IO_SAVE                 292
#define IDC_BTN_IP_SAVE_APCT            293
#define IDC_BTN_IP_SAVE_BPC             294
#define IDC_BTN_IP_SAVE_ECSERVER        295
#define IDC_BTN_IP_SAVE_ECSERVER2       296
#define IDC_BTN_IP_SAVE_NEXT            297
#define IDC_BTN_IP_SAVE_NMACHINE        298
#define IDC_BTN_LDPORT_SAVE_ECSERVER    299
#define IDC_BTN_LEFT                    300
#define IDC_BTN_LENGTH_CHANGE           301
#define IDC_BTN_LOB_TRAY                302
#define IDC_BTN_LOT_CANCEL              303
#define IDC_BTN_LOT_NO_LOAD             304
#define IDC_BTN_LOT_NO_SET              305
#define IDC_BTN_LOTNO_INIT              306
#define IDC_BTN_LOWER_TRAY              307
#define IDC_BTN_MAINTENANCE_APPLY       308
#define IDC_BTN_MANUAL                  309
#define IDC_BTN_MOTOR_MOVE_1            310
#define IDC_BTN_MOTOR_MOVE_10           311
#define IDC_BTN_MOTOR_MOVE_11           312
#define IDC_BTN_MOTOR_MOVE_12           313
#define IDC_BTN_MOTOR_MOVE_2            314
#define IDC_BTN_MOTOR_MOVE_3            315
#define IDC_BTN_MOTOR_MOVE_4            316
#define IDC_BTN_MOTOR_MOVE_5            317
#define IDC_BTN_MOTOR_MOVE_6            318
#define IDC_BTN_MOTOR_MOVE_7            319
#define IDC_BTN_MOTOR_MOVE_8            320
#define IDC_BTN_MOTOR_MOVE_9            321
#define IDC_BTN_MOTOR_PART_OPEN         322
#define IDC_BTN_MOTOR_PART_SAVE         323
#define IDC_BTN_MOTOR_POS_OPEN          324
#define IDC_BTN_MOTOR_POS_SAVE          325
#define IDC_BTN_MOTOR_SPEED             326
#define IDC_BTN_MOTTEACH_APPLY          327
#define IDC_BTN_MS_APPLY                328
#define IDC_BTN_NO                      329
#define IDC_BTN_O_GRID                  330
#define IDC_BTN_O_GRID2                 331
#define IDC_BTN_O_TEXT                  332
#define IDC_BTN_O_TEXT2                 333
#define IDC_BTN_OPERATION_FILE_DEL      334
#define IDC_BTN_OPERATION_FILE_REFRESH  335
#define IDC_BTN_PAD_0                   336
#define IDC_BTN_PAD_1                   337
#define IDC_BTN_PAD_10                  338
#define IDC_BTN_PAD_100                 339
#define IDC_BTN_PAD_1000                340
#define IDC_BTN_PAD_1001                341
#define IDC_BTN_PAD_101                 342
#define IDC_BTN_PAD_11                  343
#define IDC_BTN_PAD_2                   344
#define IDC_BTN_PAD_3                   345
#define IDC_BTN_PAD_4                   346
#define IDC_BTN_PAD_5                   347
#define IDC_BTN_PAD_6                   348
#define IDC_BTN_PAD_7                   349
#define IDC_BTN_PAD_8                   350
#define IDC_BTN_PAD_9                   351
#define IDC_BTN_PAD_BACK                352
#define IDC_BTN_PAD_DEL                 353
#define IDC_BTN_PAD_DOT                 354
#define IDC_BTN_PAD_MINUS               355
#define IDC_BTN_PAD_RESET               356
#define IDC_BTN_PARTIAL_NO              357
#define IDC_BTN_PARTIAL_YES             358
#define IDC_BTN_PASS_CHG_0              359
#define IDC_BTN_PASS_CHG_1              360
#define IDC_BTN_PASS_CHG_2              361
#define IDC_BTN_PASS_CHG_3              362
#define IDC_BTN_PASS_CHG_4              363
#define IDC_BTN_PASS_CHG_5              364
#define IDC_BTN_PASS_CHG_6              365
#define IDC_BTN_PASS_CHG_7              366
#define IDC_BTN_PASS_CHG_8              367
#define IDC_BTN_PASS_CHG_9              368
#define IDC_BTN_PASS_CHG_A              369
#define IDC_BTN_PASS_CHG_ADD            370
#define IDC_BTN_PASS_CHG_B              371
#define IDC_BTN_PASS_CHG_BACK           372
#define IDC_BTN_PASS_CHG_C              373
#define IDC_BTN_PASS_CHG_D              374
#define IDC_BTN_PASS_CHG_DEL            375
#define IDC_BTN_PASS_CHG_DIV            376
#define IDC_BTN_PASS_CHG_DOLLAR         377
#define IDC_BTN_PASS_CHG_DOT            378
#define IDC_BTN_PASS_CHG_E              379
#define IDC_BTN_PASS_CHG_F              380
#define IDC_BTN_PASS_CHG_G              381
#define IDC_BTN_PASS_CHG_H              382
#define IDC_BTN_PASS_CHG_I              383
#define IDC_BTN_PASS_CHG_J              384
#define IDC_BTN_PASS_CHG_K              385
#define IDC_BTN_PASS_CHG_L              386
#define IDC_BTN_PASS_CHG_LBRACE_B       387
#define IDC_BTN_PASS_CHG_LBRACE_S       388
#define IDC_BTN_PASS_CHG_LINE           389
#define IDC_BTN_PASS_CHG_M              390
#define IDC_BTN_PASS_CHG_N              391
#define IDC_BTN_PASS_CHG_O              392
#define IDC_BTN_PASS_CHG_P              393
#define IDC_BTN_PASS_CHG_Q              394
#define IDC_BTN_PASS_CHG_R              395
#define IDC_BTN_PASS_CHG_RBRACE_B       396
#define IDC_BTN_PASS_CHG_RBRACE_S       397
#define IDC_BTN_PASS_CHG_S              398
#define IDC_BTN_PASS_CHG_SHARP          399
#define IDC_BTN_PASS_CHG_T              400
#define IDC_BTN_PASS_CHG_U              401
#define IDC_BTN_PASS_CHG_V              402
#define IDC_BTN_PASS_CHG_W              403
#define IDC_BTN_PASS_CHG_X              404
#define IDC_BTN_PASS_CHG_Y              405
#define IDC_BTN_PASS_CHG_Z              406
#define IDC_BTN_PASS_CHK_0              407
#define IDC_BTN_PASS_CHK_1              408
#define IDC_BTN_PASS_CHK_2              409
#define IDC_BTN_PASS_CHK_3              410
#define IDC_BTN_PASS_CHK_4              411
#define IDC_BTN_PASS_CHK_5              412
#define IDC_BTN_PASS_CHK_6              413
#define IDC_BTN_PASS_CHK_7              414
#define IDC_BTN_PASS_CHK_8              415
#define IDC_BTN_PASS_CHK_9              416
#define IDC_BTN_PASS_CHK_A              417
#define IDC_BTN_PASS_CHK_ADD            418
#define IDC_BTN_PASS_CHK_B              419
#define IDC_BTN_PASS_CHK_BACK           420
#define IDC_BTN_PASS_CHK_C              421
#define IDC_BTN_PASS_CHK_D              422
#define IDC_BTN_PASS_CHK_DEL            423
#define IDC_BTN_PASS_CHK_DIV            424
#define IDC_BTN_PASS_CHK_DOLLAR         425
#define IDC_BTN_PASS_CHK_DOT            426
#define IDC_BTN_PASS_CHK_E              427
#define IDC_BTN_PASS_CHK_F              428
#define IDC_BTN_PASS_CHK_G              429
#define IDC_BTN_PASS_CHK_H              430
#define IDC_BTN_PASS_CHK_I              431
#define IDC_BTN_PASS_CHK_J              432
#define IDC_BTN_PASS_CHK_K              433
#define IDC_BTN_PASS_CHK_L              434
#define IDC_BTN_PASS_CHK_LBRACE_B       435
#define IDC_BTN_PASS_CHK_LBRACE_S       436
#define IDC_BTN_PASS_CHK_LINE           437
#define IDC_BTN_PASS_CHK_M              438
#define IDC_BTN_PASS_CHK_N              439
#define IDC_BTN_PASS_CHK_O              440
#define IDC_BTN_PASS_CHK_P              441
#define IDC_BTN_PASS_CHK_Q              442
#define IDC_BTN_PASS_CHK_R              443
#define IDC_BTN_PASS_CHK_RBRACE_B       444
#define IDC_BTN_PASS_CHK_RBRACE_S       445
#define IDC_BTN_PASS_CHK_S              446
#define IDC_BTN_PASS_CHK_SHARP          447
#define IDC_BTN_PASS_CHK_T              448
#define IDC_BTN_PASS_CHK_U              449
#define IDC_BTN_PASS_CHK_V              450
#define IDC_BTN_PASS_CHK_W              451
#define IDC_BTN_PASS_CHK_X              452
#define IDC_BTN_PASS_CHK_Y              453
#define IDC_BTN_PASS_CHK_Z              454
#define IDC_BTN_PASSWORD_CHANGE_LEVLE1  455
#define IDC_BTN_PASSWORD_CHANGE_LEVLE2  456
#define IDC_BTN_PCBOX_CHECK             457
#define IDC_BTN_PCBOX_QUERY             458
#define IDC_BTN_PICKER_INFO             459
#define IDC_BTN_PORT_SAVE_APCT          460
#define IDC_BTN_PORT_SAVE_BPC           461
#define IDC_BTN_PORT_SAVE_ECSERVER      462
#define IDC_BTN_PORT_SAVE_ECSERVER2     463
#define IDC_BTN_LOT_DISPLAY_PORT_SAVE_ECSERVER 463
#define IDC_BTN_PORT_SAVE_NEXT          464
#define IDC_BTN_ALARM_PORT_SAVE_ECSERVER 464
#define IDC_BTN_PORT_SAVE_NMACHINE      465
#define IDC_BTN_POWER_OFF_1             466
#define IDC_BTN_POWER_OFF_2             467
#define IDC_BTN_POWER_OFF_3             468
#define IDC_BTN_POWER_OFF_4             469
#define IDC_BTN_POWER_OFF_5             470
#define IDC_BTN_POWER_ON_1              471
#define IDC_BTN_POWER_ON_2              472
#define IDC_BTN_POWER_ON_3              473
#define IDC_BTN_POWER_ON_4              474
#define IDC_BTN_POWER_ON_5              475
#define IDC_BTN_PREV_ALARM_1            476
#define IDC_BTN_PREV_ALARM_10           477
#define IDC_BTN_PREV_ALARM_2            478
#define IDC_BTN_PREV_ALARM_3            479
#define IDC_BTN_PREV_ALARM_4            480
#define IDC_BTN_PREV_ALARM_5            481
#define IDC_BTN_PREV_ALARM_6            482
#define IDC_BTN_PREV_ALARM_7            483
#define IDC_BTN_PREV_ALARM_8            484
#define IDC_BTN_PREV_ALARM_9            485
#define IDC_BTN_RACK_POWER_1            486
#define IDC_BTN_RACK_POWER_2            487
#define IDC_BTN_RACK_POWER_3            488
#define IDC_BTN_RACK_POWER_4            489
#define IDC_BTN_REAR_BUFFER             490
#define IDC_BTN_REJECT_BUFFER           491
#define IDC_BTN_RETEST                  492
#define IDC_BTN_RIGHT                   493
#define IDC_BTN_SAVE                    494
#define IDC_BTN_SCRAP_INFO              495
#define IDC_BTN_SEARCH                  496
#define IDC_BTN_SEARCH2_ALARM           497
#define IDC_BTN_SEARCH_ALARM            498
#define IDC_BTN_SEARCH_BOARDOFF         499
#define IDC_BTN_SEARCH_GROUND           500
#define IDC_BTN_SEARCH_HIFIX            501
#define IDC_BTN_SEARCH_SOCKETOFF        502
#define IDC_BTN_SEARCH_TIME             503
#define IDC_BTN_SERVER_PORT_SAVE_APCT   504
#define IDC_BTN_SERVER_PORT_SAVE_FMACHINE 505
#define IDC_BTN_SET_SITE                506
#define IDC_BTN_SLAVE_ENABLE            507
#define IDC_BTN_SOCKET_CHK_TEST         508
#define IDC_BTN_STAMP_COUNT_RESET       509
#define IDC_BTN_START_TIME              510
#define IDC_BTN_STEP_SAVE               511
#define IDC_BTN_TEST                    512
#define IDC_BTN_TEST1                   512
#define IDC_BTN_TEST_APCT               513
#define IDC_BTN_TEST_BPC                514
#define IDC_BTN_TEST_ECSERVER           515
#define IDC_BTN_TEST_ECSERVER2          516
#define IDC_BTN_TEST_LOT_DISPLAY_ECSERVER 516
#define IDC_BTN_TEST_NEXT               517
#define IDC_BTN_TEST_ALARM_ECSERVER     517
#define IDC_BTN_TEST_NMACHINE           518
#define IDC_BTN_TESTER_CONNECT          519
#define IDC_BTN_TESTERIP_SAVE           520
#define IDC_BTN_TESTERPORT_SAVE         521
#define IDC_BTN_TESTREF_APPLY           522
#define IDC_BTN_TIME_OPEN               523
#define IDC_BTN_TIME_SAVE               524
#define IDC_BTN_TRACK_OUT               525
#define IDC_BTN_UNLOCK                  526
#define IDC_BTN_UPPER_TRAY              527
#define IDC_BTN_VIEW                    528
#define IDC_BTN_VIEW_PRIME              529
#define IDC_BTN_VIEW_RETEST             530
#define IDC_BTN_WAIT_APPLY              531
#define IDC_BTN_WAIT_CANCEL             532
#define IDC_BTN_YES                     533
#define IDC_BUTTON1                     534
#define IDC_BUTTON_LOTEND               534
#define IDC_BTN_ACCY_BOX1               534
#define IDC_BUTTON10                    535
#define IDC_BUTTON11                    536
#define IDC_BUTTON12                    537
#define IDC_BTN_ACCY_BOX2               537
#define IDC_BUTTON13                    538
#define IDC_BTN_ACCY_BOX3               538
#define IDC_BUTTON14                    539
#define IDC_BTN_LOT_INIT                539
#define IDC_BTN_CLAMPING_RESET          539
#define IDC_BUTTON15                    540
#define IDC_BTN_SEQ_TEST                540
#define IDC_BTN_BOX_REMOVE_SET          540
#define IDC_BUTTON16                    541
#define IDC_BTN_TT_RESET                541
#define IDC_BUTTON19                    542
#define IDC_BUTTON2                     543
#define IDC_BTN_ROBOT_GO                543
#define IDC_BUTTON_BUFFER_IN            543
#define IDC_BUTTON3                     544
#define IDC_BTN_MULTI_STACKER_GO        544
#define IDC_BUTTON_LOAD_TRAY            544
#define IDC_BUTTON4                     545
#define IDC_BUTTON_UNLOAD_TRAY          545
#define IDC_BUTTON5                     546
#define IDC_BUTTON_SOCKET_ON            546
#define IDC_BUTTON6                     547
#define IDC_BUTTON_SOCKET_OFF           547
#define IDC_BUTTON7                     548
#define IDC_BUTTON8                     549
#define IDC_BUTTON9                     550
#define IDC_CHECK_CONTROL_ENABLE        551
#define IDC_BUTTON17                    551
#define IDC_CHECK_SHOW_DETAIL_LIST      552
#define IDC_CHK_AXIS_1                  553
#define IDC_CHK_AXIS_10                 554
#define IDC_CHK_AXIS_2                  555
#define IDC_CHK_AXIS_3                  556
#define IDC_CHK_AXIS_4                  557
#define IDC_CHK_AXIS_5                  558
#define IDC_CHK_AXIS_6                  559
#define IDC_CHK_AXIS_7                  560
#define IDC_CHK_AXIS_8                  561
#define IDC_CHK_AXIS_9                  562
#define IDC_CHK_BARCODE                 563
#define IDC_CHK_BARCODE_ERROR_MODE      564
#define IDC_CHK_BOARDOFF_1              565
#define IDC_CHK_BOARDOFF_2              566
#define IDC_CHK_BOARDOFF_3              567
#define IDC_CHK_BOARDOFF_4              568
#define IDC_CHK_BOARDOFF_5              569
#define IDC_CHK_BOARDOFF_6              570
#define IDC_CHK_BTO_FAIL                571
#define IDC_CHK_BUZZER                  572
#define IDC_CHK_BYPASS                  573
#define IDC_CHK_DEBUG                   574
#define IDC_CHK_EDIT                    575
#define IDC_CHK_DUMPING                 575
#define IDC_CHK_FAIL_BTO                576
#define IDC_CHK_DELETE                  576
#define IDC_CHK_SESS                    576
#define IDC_CHK_FAIL_FAIL               577
#define IDC_CHK_USS_AUTO_DELETE_SESS    577
#define IDC_CHK_FAIL_HTO                578
#define IDC_CHK_CIM_RCMD_CHK            578
#define IDC_CHK_FAIL_NTO                579
#define IDC_CHK_CIM_MODE                579
#define IDC_CHK_HTO_FAIL                580
#define IDC_CHK_INTERFACE               581
#define IDC_CHK_LENGTH_CHANGE           582
#define IDC_CHK_NTO_FAIL                583
#define IDC_CHK_RACK_SKIP_1             584
#define IDC_CHK_RACK_SKIP_2             585
#define IDC_CHK_RACK_SKIP_3             586
#define IDC_CHK_RACK_SKIP_4             587
#define IDC_CHK_RETEST                  588
#define IDC_CHK_REVERSE                 589
#define IDC_CHK_ULD_CONVAYOR            590
#define IDC_CHK_VIRTUAL                 591
#define IDC_COMBO_LOTNAME               592
#define IDC_CHK_CE_MODE                 592
#define IDC_CST_BARCODE_FRONT           593
#define IDC_CHK_ALIGN                   593
#define IDC_CST_BARCODE_REAR            594
#define IDC_CHK_STACK_PASS_MODE         594
#define IDC_CST_BARCODE_SAFETY          595
#define IDC_CHK_PARTNO_CHECK            595
#define IDC_CST_BUFFER_IN               596
#define IDC_CHK_PROPERTY_PASS_MODE      596
#define IDC_CST_BUFFER_OUT              597
#define IDC_CST_COUNT_BIN               598
#define IDC_CST_COUNT_TEST              599
#define IDC_CST_COUNT_WORK              600
#define IDC_CST_FCT_HANDLER_SCRAP_INFO  601
#define IDC_CST_FRONT_IN_BUFFER         602
#define IDC_CST_FRONT_OUT_BUFFER        603
#define IDC_CST_FRONT_RACK_1_L          604
#define IDC_CST_FRONT_RACK_1_R          605
#define IDC_CST_FRONT_RACK_2_L          606
#define IDC_CST_FRONT_RACK_2_R          607
#define IDC_CST_FRONT_SHIFTER           608
#define IDC_CST_LOT_TIME                609
#define IDC_CST_P_EJECT                 610
#define IDC_CST_P_PICK                  611
#define IDC_CST_P_PLACE                 612
#define IDC_CST_PCT_SORTER_SCRAP_INFO   613
#define IDC_CST_RACK_FRONT_1            614
#define IDC_CST_RACK_FRONT_1_L          615
#define IDC_CST_RACK_FRONT_1_R          616
#define IDC_CST_RACK_FRONT_2            617
#define IDC_CST_RACK_FRONT_2_L          618
#define IDC_CST_RACK_FRONT_2_R          619
#define IDC_CST_RACK_REAR_1             620
#define IDC_CST_RACK_REAR_1_L           621
#define IDC_CST_RACK_REAR_1_R           622
#define IDC_CST_RACK_REAR_2             623
#define IDC_CST_RACK_REAR_2_L           624
#define IDC_CST_RACK_REAR_2_R           625
#define IDC_CST_REAR_IN_BUFFER          626
#define IDC_CST_REAR_OUT_BUFFER         627
#define IDC_CST_REAR_RACK_1_L           628
#define IDC_CST_REAR_RACK_1_R           629
#define IDC_CST_REAR_RACK_2_L           630
#define IDC_CST_REAR_RACK_2_R           631
#define IDC_CST_REAR_SHIFTER            632
#define IDC_CST_ROUTER_SORTER_SCRAP_INFO 633
#define IDC_CST_SERVER_SCRAP_INFO       634
#define IDC_CST_SITE_TEST_INFO          635
#define IDC_CST_SORTER_SCRAP_INFO       636
#define IDC_CST_SORTER_SCRAP_LIST       637
#define IDC_CST_UPH                     638
#define IDC_CST_X_LD_BUFFER             639
#define IDC_CST_X_SITE_1                640
#define IDC_CST_X_SITE_2                641
#define IDC_CST_X_SITE_3                642
#define IDC_CST_X_SITE_4                643
#define IDC_CST_X_ULD_BUFFER            644
#define IDC_CST_Z_BUFFER_PICK           645
#define IDC_CST_Z_BUFFER_PLACE          646
#define IDC_CST_Z_EJECT                 647
#define IDC_CST_Z_PICK                  648
#define IDC_CST_Z_PLACE                 649
#define IDC_CST_Z_PRESS                 650
#define IDC_CST_Z_SAFETY                651
#define IDC_CURSOR1                     652
#define IDC_CURSOR2                     653
#define IDC_CUSTOM1                     654
#define IDC_CUSTOM_BARCODE_TRAY         654
#define IDC_CUSTOM_ULD_STACKER_TRAY     654
#define IDC_CUSTOM_BIN_STACKER_2_STATUS 654
#define IDC_CUSTOM_BASIC                654
#define IDC_CUSTOM_DOOR_TOP1_BTM9       654
#define IDC_CUSTOM4                     655
#define IDC_CUSTOM_BIN_STACKER_3_STATUS 655
#define IDC_CUSTOM_SUPPLY_INFO          655
#define IDC_CUSTOM_AIR_BLOW             656
#define IDC_CUSTOM_BIN_STACKER_1_STATUS 656
#define IDC_CUSTOM_B_LOT_INFO           657
#define IDC_CUSTOM_BIN_CNT              658
#define IDC_CUSTOM_BUFFER               659
#define IDC_CUSTOM_DOOR_TOP2_BTM10      659
#define IDC_CUSTOM_CUSTOMER_BUFFER      660
#define IDC_CUSTOM_DOOR_TOP3_BTM11      660
#define IDC_CUSTOM_DAILY_YIELD_INFO     661
#define IDC_CUSTOM_DOOR_TOP4_BTM12      661
#define IDC_CUSTOM_DATA                 662
#define IDC_CUSTOM_BIN_INFO             662
#define IDC_CUSTOM_DOOR_TOP5_BTM13      662
#define IDC_CUSTOM_DEVICE               663
#define IDC_CUSTOM_TRAY_LOAD_PLATE      663
#define IDC_CUSTOM_DOOR_TOP6_BTM14      663
#define IDC_CUSTOM_FILE_INFO            664
#define IDC_CUSTOM_BIN_PLATE_4          664
#define IDC_CUSTOM_DOOR_TOP7_BTM15      664
#define IDC_CUSTOM_FRONT_BUFFER         665
#define IDC_CUSTOM_BIN_PLATE_3          665
#define IDC_CUSTOM_DOOR_TOP8_BTM16      665
#define IDC_CUSTOM_INPUT                666
#define IDC_CUSTOM_BIN_PLATE_2          666
#define IDC_CUSTOM_GRIPPER_INFO         666
#define IDC_CUSTOM_IO                   667
#define IDC_CUSTOM_BIN_PLATE_1          667
#define IDC_CUSTOM_LIST                 668
#define IDC_CUSTOM_GOOD_PLATE           668
#define IDC_CUSTOM_LOB_BUFFER           669
#define IDC_CUSTOM_TRAY_TRANSFER        669
#define IDC_CUSTOM_LOB_BUFFER_L         670
#define IDC_CUSTOM_BUFFER_2             670
#define IDC_CST_DOOR                    670
#define IDC_CUSTOM_LOB_BUFFER_R         671
#define IDC_CUSTOM_BUFFER_1             671
#define IDC_CUSTOM_EMPTY_PLATE          671
#define IDC_CUSTOM_LOT                  672
#define IDC_CUSTOM_LD_SHIFTER           672
#define IDC_CUSTOM_LOB_STACKER          672
#define IDC_CUSTOM_LOT_INFO             673
#define IDC_CUSTOM_LOT_YIELD_INFO       674
#define IDC_CUSTOM_LOWER_TRAT_L         675
#define IDC_CUSTOM_ULD_SHIFTER          675
#define IDC_CUSTOM_BIN_STACKER_3        675
#define IDC_CUSTOM_LOWER_TRAY_R         676
#define IDC_CUSTOM_BIN_STACKER_2        676
#define IDC_CUSTOM_MOTOR                677
#define IDC_CUSTOM_FLIPPER              677
#define IDC_CUSTOM_BIN_STACKER_1        677
#define IDC_CUSTOM_MOTOR_INFO           678
#define IDC_CUSTOM_GOOD_STACKER         678
#define IDC_CUSTOM_MOTOR_PART           679
#define IDC_CUSTOM_MULTI_STACKER        679
#define IDC_CUSTOM_MOTOR_POS            680
#define IDC_CUSTOM_EMPTY_STACKER        680
#define IDC_CUSTOM_MOTOR_SPEED          681
#define IDC_CUSTOM_SMEMA_INFO           681
#define IDC_CUSTOM_MOTOR_VARIABLE_SPEED 682
#define IDC_CUSTOM_MULTI_BIN_3          682
#define IDC_CUSTOM_OUTPUT               683
#define IDC_CUSTOM_MULTI_BIN_1          683
#define IDC_CUSTOM_PICKER               684
#define IDC_CUSTOM_REAR_BUFFER          685
#define IDC_CUSTOM_MULTI_BIN_2          685
#define IDC_CUSTOM_REJECT_BUFFER        686
#define IDC_CUSTOM_LOB_RAIL             686
#define IDC_CUSTOM_REJECT_BUFFER_L      687
#define IDC_CUSTOM_BIN_STACKER          687
#define IDC_CUSTOM_UPH                  687
#define IDC_CUSTOM_REJECT_BUFFER_R      688
#define IDC_CUSTOM_RETEST_BUFFER        689
#define IDC_CUSTOM_TIME                 690
#define IDC_CUSTOM_TRAY_1               691
#define IDC_CUSTOM_TRAY_2               692
#define IDC_CUSTOM_UPPER_TRAY_L         693
#define IDC_CUSTOM_UPPER_TRAY_R         694
#define IDC_CUSTOM_WORK_CNT             695
#define IDC_DATA_ALARM_CODE             696
#define IDC_DATA_ALARM_TIME             697
#define IDC_DATA_ALARM_TYPE             698
#define IDC_DGT_ABSOLUTE_YIELD          699
#define IDC_DGT_ALARM                   700
#define IDC_DGT_ALARM_DELAY_TIME        701
#define IDC_DGT_MTBI                    701
#define IDC_DGT_ALARM_TIME              702
#define IDC_DGT_BARCODE_READ_CNT        703
#define IDC_DGT_BARCODE_READ_ERR_CNT    704
#define IDC_DGT_BD_LIVE_CHECK_GAP       705
#define IDC_DGT_BOARD_APPLY_COUNT       706
#define IDC_DGT_BOARD_COUNT_MAX         707
#define IDC_DGT_BRUN_TIME               708
#define IDC_DGT_BTO_TIME                709
#define IDC_DGT_CHANGE_TIME             710
#define IDC_DGT_CONTINUITY_COUNT        711
#define IDC_DGT_CURRENT_POS_1           712
#define IDC_DGT_CURRENT_POS_2           713
#define IDC_DGT_CURRENT_POS_3           714
#define IDC_DGT_CURRENT_POS_4           715
#define IDC_DGT_CURRENT_POS_5           716
#define IDC_DGT_EJECT_COUNT             717
#define IDC_DGT_ELECTROSTATIC_CHECK_GAP 718
#define IDC_DGT_ELECTROSTATIC_CHECK_VALUE 719
#define IDC_DGT_FLICKER_TIME            720
#define IDC_DGT_GROUND_ALLOW            721
#define IDC_DGT_GROUND_RESULT1          722
#define IDC_DGT_GROUND_RESULT2          723
#define IDC_DGT_GROUND_RESULT3          724
#define IDC_DGT_GROUND_RESULT4          725
#define IDC_DGT_GROUND_RESULT5          726
#define IDC_DGT_GROUND_VALUE            727
#define IDC_DGT_HTO_MAX_TIME            728
#define IDC_DGT_HTO_TIME                729
#define IDC_DGT_LINE_YIELD              730
#define IDC_DGT_MACHINE_YIELD           731
#define IDC_DGT_MANUAL_RATE             732
#define IDC_DGT_NETWORK_RETRY_COUNT     733
#define IDC_DGT_NETWORK_WAIT_TIME       734
#define IDC_DGT_NEW_VALUE               735
#define IDC_DGT_EJECT_RETRY_COUNT       735
#define IDC_DGT_NTO_TIME                736
#define IDC_DGT_OFFLINE_TEST_TIME       737
#define IDC_DGT_OLD_VALUE               738
#define IDC_DGT_P_INDEX_TIME_FRONT_RACK_1_L 739
#define IDC_DGT_P_INDEX_TIME_FRONT_RACK_1_R 740
#define IDC_DGT_P_INDEX_TIME_FRONT_RACK_2_L 741
#define IDC_DGT_P_INDEX_TIME_FRONT_RACK_2_R 742
#define IDC_DGT_P_INDEX_TIME_REAR_RACK_1_L 743
#define IDC_DGT_P_INDEX_TIME_REAR_RACK_1_R 744
#define IDC_DGT_P_INDEX_TIME_REAR_RACK_2_L 745
#define IDC_DGT_P_INDEX_TIME_REAR_RACK_2_R 746
#define IDC_DGT_PCB_SIZE_X              747
#define IDC_DGT_PCB_SIZE_Y              748
#define IDC_DGT_PICK_COUNT              749
#define IDC_DGT_PRESS_COUNT             750
#define IDC_DGT_RELATIVE_YIELD          751
#define IDC_DGT_RETEST_COUNT            752
#define IDC_DGT_RETRY_WAIT              753
#define IDC_DGT_RUN                     754
#define IDC_DGT_RUN_RATE                755
#define IDC_DGT_RUN_TIME                756
#define IDC_DGT_STAMP_CHECK             757
#define IDC_DGT_STAMP_LIMIT             758
#define IDC_DGT_STATIC_ELECTRICITY_CHECK_GAP 759
#define IDC_DGT_STATION_APPLY_COUNT     760
#define IDC_DGT_STATION_YIELD           761
#define IDC_DGT_STOP                    762
#define IDC_DGT_STOP_TIME               763
#define IDC_DGT_TRAY_X                  764
#define IDC_DGT_TRAY_Y                  765
#define IDC_DGT_WRUN_TIME               766
#define IDC_DGT_BOAT_X                  766
#define IDC_DGT_DISTANCE                766
#define IDC_EDIT_A4200_SC               767
#define IDC_DGT_BOAT_Y                  767
#define IDC_DGT_BRIGHTNESS              767
#define IDC_EDIT_A4201_SC               768
#define IDC_DGT_SHUTTER_TIME            768
#define IDC_EDIT_A4202_SC               769
#define IDC_DGT_CONTRAST                769
#define IDC_EDIT_ALARM_REPARE           770
#define IDC_DGT_CODE_LENTH              770
#define IDC_EDIT_ALARM_TITLE            771
#define IDC_EDIT_ALOT_NO                772
#define IDC_EDIT_AS_SC                  773
#define IDC_EDIT_BLOT_NO                774
#define IDC_EDIT_BOARD_DATA             775
#define IDC_EDIT_CLOT_NO                776
#define IDC_EDIT_DEVICE_TYPE            777
#define IDC_EDIT_EQUIP_ID               778
#define IDC_EDIT_EQUIP_NO               779
#define IDC_EDIT_FRONT_BUFFER           780
#define IDC_EDIT_EC_EQUIP_ID            780
#define IDC_EDIT_FRONT_SITE             781
#define IDC_EDIT_FRONT_STATION          782
#define IDC_EDIT_FTP_PATH               783
#define IDC_EDIT_FTPID                  784
#define IDC_EDIT_FTPPASSWORD            785
#define IDC_EDIT_FTPPORT                786
#define IDC_EDIT_KEYPAD_TITLE           787
#define IDC_EDIT_LDPORT_ECSERVER        788
#define IDC_EDIT_LOB_TRAY               789
#define IDC_EDIT_LOWER_TRAY             790
#define IDC_EDIT_OPERATION_DISPLAY      791
#define IDC_EDIT_PASS_CHG_NEW           792
#define IDC_EDIT_PASS_CHG_OLD           793
#define IDC_EDIT_PASS_CHG_VERIFY        794
#define IDC_EDIT_PASS_CHK_DATA          795
#define IDC_EDIT_PICKER_INFO            796
#define IDC_EDIT_PORT_APCT              797
#define IDC_EDIT_PORT_BPC               798
#define IDC_EDIT_PORT_ECSERVER          799
#define IDC_EDIT_PORT_ECSERVER2         800
#define IDC_EDIT_LOT_DISPLAY_PORT_ECSERVER 800
#define IDC_EDIT_PORT_NEXT              801
#define IDC_EDIT_ALARM_PORT_ECSERVER    801
#define IDC_EDIT_PORT_NMACHINE          802
#define IDC_EDIT_REAR_BUFFER            803
#define IDC_EDIT_REAR_SITE              804
#define IDC_EDIT_REAR_STATION           805
#define IDC_EDIT_REJECT_BUFFER          806
#define IDC_EDIT_RETEST                 807
#define IDC_EDIT_SEQ_MSG                808
#define IDC_EDIT_SERIAL                 809
#define IDC_EDIT_SERVER_PORT_APCT       810
#define IDC_EDIT_SERVER_PORT_FMACHINE   811
#define IDC_EDIT_TESTERPORT             812
#define IDC_EDIT_UPPER_TRAY             813
#define IDC_END_DATE                    814
#define IDC_END_TIME                    815
#define IDC_FTPIPADDRESS                816
#define IDC_GALMG_TEST                  817
#define IDC_GIF_ALARM                   818
#define IDC_GIF_EXIT                    819
#define IDC_GIF_INFO                    820
#define IDC_GIF_INITIALIZING            821
#define IDC_GIF_LOCK                    822
#define IDC_GIF_M_MESSAGE               823
#define IDC_GIF_MENU                    824
#define IDC_GIF_MESSAGE                 825
#define IDC_GIF_SELECT                  826
#define IDC_GIF_TITLE_LOGO              827
#define IDC_GROUP_ADD_4200_SCRAP_TO_SERVER 828
#define IDC_GROUP_ADD_4201_SCRAP_TO_SERVER 829
#define IDC_GROUP_ADD_4202_SCRAP_TO_SERVER 830
#define IDC_GROUP_ADD_SCRAP_TO_SERVER   831
#define IDC_GROUP_AIR_BLOW_BOX          832
#define IDC_GROUP_ALARM_DELAY_TIME      833
#define IDC_GROUP_ALARM_INFO            834
#define IDC_GROUP_APCT_TYPE             835
#define IDC_GROUP_AUTO_OFF_MODE         836
#define IDC_GROUP_AXIS_INFO             837
#define IDC_GROUP_B_LOT_INFO            838
#define IDC_GROUP_BARCODE               839
#define IDC_GROUP_BARCODE_ERROR_MODE    840
#define IDC_GROUP_BARCODE_READ_COUNT    841
#define IDC_GROUP_BARCODE_READ_ERR_CNT  842
#define IDC_GROUP_BD_LIVE_CHECK_GAP     843
#define IDC_GROUP_BIN_CNT               844
#define IDC_GROUP_BIN_COUNT             845
#define IDC_GROUP_BOARD                 846
#define IDC_GROUP_BOARD_COUNT_MAX       847
#define IDC_GROUP_BOARD_OFF_MODE        848
#define IDC_GROUP_BPC_SET               849
#define IDC_GROUP_BTO_TIME              850
#define IDC_GROUP_BUFFER                851
#define IDC_GROUP_BUTTON_SETTING        852
#define IDC_GROUP_BUZZER                853
#define IDC_GROUP_BYPASS                854
#define IDC_GROUP_CONTI_OP              855
#define IDC_GROUP_CONTROL_PANEL         856
#define IDC_GROUP_DAILY_YIELD_INFO      857
#define IDC_GROUP_DATA                  858
#define IDC_GROUP_BIN_INFO              858
#define IDC_GROUP_DATA_BACKUP           859
#define IDC_GROUP_DEVICE                860
#define IDC_GROUP_DEVICE_MODE           861
#define IDC_GROUP_DEVICE_TYPE           862
#define IDC_GROUP_TURN_MODE             862
#define IDC_GROUP_EC_SERVER_SET         863
#define IDC_GROUP_EC_SERVER_SET2        864
#define IDC_GROUP_REVERSE_MODE          864
#define IDC_GROUP_EJECTOR               865
#define IDC_GROUP_PICKER_TURN_MODE      865
#define IDC_GROUP_EJECTOR_REPEAT_CNT    866
#define IDC_GROUP_PICKER_MODE           866
#define IDC_GROUP_PICKER_USE_MODE       866
#define IDC_GROUP_ELECTROSTATIC_CHECK_GAP 867
#define IDC_GROUP_ELECTROSTATIC_CHECK_VALUE 868
#define IDC_GROUP_ELECTROSTATIC_TEST    869
#define IDC_GROUP_END_DATE              870
#define IDC_GROUP_EQP_SET               871
#define IDC_GROUP_FCT_HANDLER_SCRAP_INFO 872
#define IDC_GROUP_FILE_INFO             873
#define IDC_GROUP_FRONT_BUFFER          874
#define IDC_GROUP_FRONT_IN_BUFFER       875
#define IDC_GROUP_FRONT_OUT_BUFFER      876
#define IDC_GROUP_FRONT_RACK_1          877
#define IDC_GROUP_FRONT_RACK_2          878
#define IDC_GROUP_FRONT_SHIFTER         879
#define IDC_GROUP_FTP_SET               880
#define IDC_GROUP_GROUND_ALLOW          881
#define IDC_GROUP_GROUND_TEST           882
#define IDC_GROUP_GROUND_VALUE          883
#define IDC_GROUP_HTO_MAX_TIME          884
#define IDC_GROUP_HTO_TIME              885
#define IDC_GROUP_INFO_SELECT           886
#define IDC_GROUP_INPUT                 887
#define IDC_GROUP_INTERFACE             888
#define IDC_GROUP_IO                    889
#define IDC_GROUP_IO_PART               890
#define IDC_GROUP_KEYPAD                891
#define IDC_GROUP_LAMP_ALARM            892
#define IDC_GROUP_LAMP_CHANGE_TIME      893
#define IDC_GROUP_LAMP_FLICKER_TIME     894
#define IDC_GROUP_LAMP_INITIAL          895
#define IDC_GROUP_LAMP_LOCK             896
#define IDC_GROUP_LAMP_LOTEND           897
#define IDC_GROUP_LAMP_RUN              898
#define IDC_GROUP_LAMP_SELFCHECK        899
#define IDC_GROUP_LAMP_STOP             900
#define IDC_GROUP_LAMP_WARNING          901
#define IDC_GROUP_LOB_BUFFER            902
#define IDC_GROUP_LOT_INFO              903
#define IDC_GROUP_LOT_NO                904
#define IDC_GROUP_LOT_TIME              905
#define IDC_GROUP_LOT_YIELD_INFO        906
#define IDC_GROUP_LOWER_TRAY            907
#define IDC_GROUP_MLCT_MODE             908
#define IDC_GROUP_MOT_BARCODE           909
#define IDC_GROUP_MOT_BUFFER            910
#define IDC_GROUP_MOT_SHIFTER_LENGTH    911
#define IDC_GROUP_MOT_SHIFTER_X         912
#define IDC_GROUP_MOT_SHIFTER_Z         913
#define IDC_GROUP_MOTOR                 914
#define IDC_GROUP_MOTOR_PART            915
#define IDC_GROUP_MOTOR_POS             916
#define IDC_GROUP_MOTOR_POWER_1         917
#define IDC_GROUP_MOTOR_POWER_2         918
#define IDC_GROUP_MOTOR_POWER_3         919
#define IDC_GROUP_MOTOR_POWER_4         920
#define IDC_GROUP_MOTOR_POWER_5         921
#define IDC_GROUP_MOTOR_SPEED_RATE      922
#define IDC_GROUP_MOTOR_SPEED_SET       923
#define IDC_GROUP_MOTOR_VARIABLE_SPEED_SET 924
#define IDC_GROUP_MOVE                  925
#define IDC_GROUP_NETWORK_RETRY_COUNT   926
#define IDC_GROUP_NETWORK_WAIT_TIME     927
#define IDC_GROUP_NEXT_APCT_SET         928
#define IDC_GROUP_EJECT_RETRY_COUNT     928
#define IDC_GROUP_NEXT_MACHINE          928
#define IDC_GROUP_NEXT_MACHINE_SET      929
#define IDC_GROUP_BCR_SELECT            929
#define IDC_GROUP_NTO_TIME              930
#define IDC_GROUP_PICKER_CHK            930
#define IDC_GROUP_OFFLINE_TEST_TIME     931
#define IDC_GROUP_OPERATION_LIST        932
#define IDC_GROUP_OPERATION_TYPE        933
#define IDC_GROUP_OUTPUT                934
#define IDC_GROUP_PART                  935
#define IDC_GROUP_PART_INFORMATION      936
#define IDC_GROUP_PASS_CHG              937
#define IDC_GROUP_PASS_CHK              938
#define IDC_GROUP_PASSWORD_CHANGE       939
#define IDC_GROUP_PCB_SIZE              940
#define IDC_GROUP_NETWORK_ADDR          940
#define IDC_GROUP_PCT_SORTER_SCRAP_INFO 941
#define IDC_GROUP_PICKER                942
#define IDC_GROUP_PRESS_COUNT           943
#define IDC_GROUP_PREV_ALARM            944
#define IDC_GROUP_QUESTION              945
#define IDC_GROUP_REAR_BUFFER           946
#define IDC_GROUP_REAR_IN_BUFFER        947
#define IDC_GROUP_REAR_OUT_BUFFER       948
#define IDC_GROUP_REAR_RACK_1           949
#define IDC_GROUP_REAR_RACK_2           950
#define IDC_GROUP_REAR_SHIFTER          951
#define IDC_GROUP_RECIPE_SELECT         952
#define IDC_GROUP_REJECT_BUFFER         953
#define IDC_GROUP_RETEST                954
#define IDC_GROUP_RETEST_BUFFER         955
#define IDC_GROUP_RETEST_CALL_MODE      956
#define IDC_GROUP_RETEST_COUNT          957
#define IDC_GROUP_RETEST_MODE           958
#define IDC_GROUP_ROUTER_SORTER_SCRAP_INFO 959
#define IDC_GROUP_RUN_MODE              960
#define IDC_GROUP_SERVER_SCRAP_LIST     961
#define IDC_GROUP_SHIFTER_LENGTH        962
#define IDC_GROUP_SHIFTER_X             963
#define IDC_GROUP_SHIFTER_Z             964
#define IDC_GROUP_SITE_TEST_INFO        965
#define IDC_GROUP_SORTER_SCRAP_INFO     966
#define IDC_GROUP_SORTER_SCRAP_LIST     967
#define IDC_GROUP_STAMP_CHECK           968
#define IDC_GROUP_STAMP_LIMIT           969
#define IDC_GROUP_START_DATE            970
#define IDC_GROUP_STATIC_ELECTRICITY_CHECK_GAP 971
#define IDC_GROUP_STATION_OFF_MODE      972
#define IDC_GROUP_TEST_COUNT            973
#define IDC_GROUP_TEST_TIME             974
#define IDC_GROUP_TESTER_SET            975
#define IDC_GROUP_TIME                  976
#define IDC_GROUP_TIME_INFO             977
#define IDC_GROUP_TOWERLAMP             978
#define IDC_GROUP_REQ_INFO              978
#define IDC_GROUP_TRAY_SIZE_SETTING     979
#define IDC_GROUP_SUPPLY_INFO           979
#define IDC_GROUP_UPH                   980
#define IDC_GROUP_BOAT_SIZE_SETTING     980
#define IDC_GROUP_BCR_STATE_SETTING     980
#define IDC_GROUP_UPPER_TRAY            981
#define IDC_GROUP_WORK_CNT              982
#define IDC_GROUP_WORK_COUNT            983
#define IDC_GROUP_WORK_MODE             984
#define IDC_IMAGE_ALARM                 985
#define IDC_INFO_MESSAGE                986
#define IDC_IO_BARCODE_SAFETY           987
#define IDC_IO_BC_DN                    988
#define IDC_IO_BC_UP                    989
#define IDC_IO_HOME_1                   990
#define IDC_IO_HOME_2                   991
#define IDC_IO_HOME_3                   992
#define IDC_IO_HOME_4                   993
#define IDC_IO_HOME_5                   994
#define IDC_IO_LEFT_DN                  995
#define IDC_IO_LEFT_UP                  996
#define IDC_IO_ML_1                     997
#define IDC_IO_ML_2                     998
#define IDC_IO_ML_3                     999
#define IDC_IO_ML_4                     1000
#define IDC_MSG_HOST_CONNECTOR          1000
#define IDC_IO_ML_5                     1001
#define IDC_IO_MOTOR_ALARM_1            1002
#define IDC_MSG_EQ_CONNECTOR            1002
#define IDC_IO_MOTOR_ALARM_2            1003
#define IDC_MSG_MACHINE_STATUS          1003
#define IDC_IO_MOTOR_ALARM_3            1004
#define IDC_IO_MOTOR_ALARM_4            1005
#define IDC_IO_MOTOR_ALARM_5            1006
#define IDC_BUTTON_INITIALIZE           1006
#define IDC_IO_MOTOR_POWER_1            1007
#define IDC_BUTTON_OFFLINE              1007
#define IDC_IO_MOTOR_POWER_2            1008
#define IDC_BUTTON_ONLINE_LOCAL         1008
#define IDC_IO_MOTOR_POWER_3            1009
#define IDC_BUTTON_ONLINE_REMOTE        1009
#define IDC_IO_MOTOR_POWER_4            1010
#define IDC_BUTTON_ALARM_SET            1010
#define IDC_IO_MOTOR_POWER_5            1011
#define IDC_BUTTON_ALARM_CLEAR          1011
#define IDC_IO_PL_1                     1012
#define IDC_BUTTON_STOP                 1012
#define IDC_IO_PL_2                     1013
#define IDC_BUTTON_RUN                  1013
#define IDC_IO_PL_3                     1014
#define IDC_BUTTON_LOTSTART             1014
#define IDC_IO_PL_4                     1015
#define IDC_EDIT1                       1015
#define IDC_IO_PL_5                     1016
#define IDC_EDIT2                       1016
#define IDC_IO_RACK_POWER_1             1017
#define IDC_IO_RACK_POWER_2             1018
#define IDC_IO_RACK_POWER_3             1019
#define IDC_IO_RACK_POWER_4             1020
#define IDC_BUTTON_PPID                 1020
#define IDC_IO_RIGHT_DN                 1021
#define IDC_IO_RIGHT_UP                 1022
#define IDC_IPADDRESS_APCT              1023
#define IDC_IPADDRESS_BPC               1024
#define IDC_IPADDRESS_ECSERVER          1025
#define IDC_IPADDRESS_ECSERVER2         1026
#define IDC_IPADDRESS_NEXT              1027
#define IDC_IPADDRESS_NMACHINE          1028
#define IDC_JOG_MINUS_1                 1029
#define IDC_JOG_MINUS_2                 1030
#define IDC_JOG_MINUS_3                 1031
#define IDC_JOG_MINUS_4                 1032
#define IDC_JOG_MINUS_5                 1033
#define IDC_JOG_PLUS_1                  1034
#define IDC_JOG_PLUS_2                  1035
#define IDC_JOG_PLUS_3                  1036
#define IDC_JOG_PLUS_4                  1037
#define IDC_JOG_PLUS_5                  1038
#define IDC_LABEL_A4200_SC              1039
#define IDC_LABEL_A4201_SC              1040
#define IDC_LABEL_A4202_SC              1041
#define IDC_LABEL_ABSOLUTE_YIELD        1042
#define IDC_LABEL_AS_SC                 1043
#define IDC_LABEL_BOARD_APPLY_COUNT     1044
#define IDC_LABEL_CONTINUITY_COUNT      1045
#define IDC_LABEL_CUSTOMER_BUFFER       1046
#define IDC_LABEL_DEVICE_NAME           1047
#define IDC_LABEL_ELECTROSTATIC_1       1048
#define IDC_LABEL_ELECTROSTATIC_2       1049
#define IDC_LABEL_ELECTROSTATIC_3       1050
#define IDC_LABEL_ELECTROSTATIC_4       1051
#define IDC_LABEL_ELECTROSTATIC_5       1052
#define IDC_LABEL_EQP_ID                1053
#define IDC_LABEL_EQP_NO                1054
#define IDC_LABEL_EVENT_MSG             1055
#define IDC_LABEL_FRONT_BUFFER          1056
#define IDC_LABEL_LINE_YIELD            1057
#define IDC_LABEL_LOB                   1058
#define IDC_LABEL_MACHINE_POS           1059
#define IDC_LABEL_MACHINE_YIELD         1060
#define IDC_LABEL_PCB_X                 1061
#define IDC_LABEL_PCB_Y                 1062
#define IDC_LABEL_PICKER                1063
#define IDC_LABEL_REAR_BUFFER           1064
#define IDC_LABEL_REJECT_BUFFER         1065
#define IDC_LABEL_RELATIVE_YIELD        1066
#define IDC_LABEL_RETEST_BUFFER         1067
#define IDC_LABEL_SERIAL                1068
#define IDC_LABEL_STATION_APPLY_COUNT   1069
#define IDC_LABEL_STATION_YIELD         1070
#define IDC_LABEL_TITLE                 1071
#define IDC_LABEL_TRAY_1                1072
#define IDC_LABEL_TRAY_2                1073
#define IDC_LAMP_ALARM                  1074
#define IDC_LAMP_INITIAL                1075
#define IDC_LAMP_LOCK                   1076
#define IDC_LAMP_LOTEND                 1077
#define IDC_LAMP_RUN                    1078
#define IDC_LAMP_SELFCHECK              1079
#define IDC_LAMP_STOP                   1080
#define IDC_LAMP_WARNING                1081
#define IDC_LIST1                       1082
#define IDC_LIST_CLOCK                  1083
#define IDC_LIST_DATA                   1084
#define IDC_LIST_DEVICE_TYPE            1085
#define IDC_LIST_MENU                   1086
#define IDC_LIST_OPERATION_FILE         1087
#define IDC_MONTHCAL_OPERATION          1088
#define IDC_MOTOR_IMG                   1089
#define IDC_MSG_ALARM                   1090
#define IDC_MSG_ALARM_CODE              1091
#define IDC_MSG_MTBI                    1091
#define IDC_MSG_ALARM_REPARE            1092
#define IDC_MSG_ALARM_TIME              1093
#define IDC_MSG_ALARM_TITLE             1094
#define IDC_MSG_ALARM_TYPE              1095
#define IDC_MSG_BOARD                   1096
#define IDC_MSG_BRUN_TIME               1097
#define IDC_MSG_CURRENT_POS_1           1098
#define IDC_MSG_CURRENT_POS_2           1099
#define IDC_MSG_CURRENT_POS_3           1100
#define IDC_MSG_CURRENT_POS_4           1101
#define IDC_MSG_CURRENT_POS_5           1102
#define IDC_MSG_DEVICE_NAME             1103
#define IDC_MSG_ELECTROSTATIC_1         1104
#define IDC_MSG_ELECTROSTATIC_2         1105
#define IDC_MSG_ELECTROSTATIC_3         1106
#define IDC_MSG_ELECTROSTATIC_4         1107
#define IDC_MSG_ELECTROSTATIC_5         1108
#define IDC_MSG_EQP_ID                  1109
#define IDC_MSG_EQP_NO                  1110
#define IDC_MSG_EQUIP_ID                1111
#define IDC_MSG_EQUIP_NO                1112
#define IDC_MSG_EXIT                    1113
#define IDC_MSG_EC_EQUIP_ID             1113
#define IDC_MSG_FORM_NAME               1114
#define IDC_MSG_FRONT_REAR              1115
#define IDC_MSG_FTP_PATH                1116
#define IDC_MSG_FTPID                   1117
#define IDC_MSG_FTPIPADDRESS            1118
#define IDC_MSG_FTPPASSWORD             1119
#define IDC_MSG_FTPPORT                 1120
#define IDC_MSG_GROUND_1                1121
#define IDC_MSG_GROUND_2                1122
#define IDC_MSG_GROUND_3                1123
#define IDC_MSG_GROUND_4                1124
#define IDC_MSG_GROUND_5                1125
#define IDC_MSG_INDEX_TIME_FRONT_RACK_1_L 1126
#define IDC_MSG_INDEX_TIME_FRONT_RACK_1_R 1127
#define IDC_MSG_INDEX_TIME_FRONT_RACK_2_L 1128
#define IDC_MSG_INDEX_TIME_FRONT_RACK_2_R 1129
#define IDC_MSG_INDEX_TIME_REAR_RACK_1_L 1130
#define IDC_MSG_INDEX_TIME_REAR_RACK_1_R 1131
#define IDC_MSG_INDEX_TIME_REAR_RACK_2_L 1132
#define IDC_MSG_INDEX_TIME_REAR_RACK_2_R 1133
#define IDC_MSG_INITIAL                 1134
#define IDC_MSG_IPADDRESS_APCT          1135
#define IDC_MSG_IPADDRESS_BPC           1136
#define IDC_MSG_IPADDRESS_ECSERVER      1137
#define IDC_MSG_IPADDRESS_ECSERVER2     1138
#define IDC_MSG_IPADDRESS_NEXT          1139
#define IDC_MSG_IPADDRESS_NMACHINE      1140
#define IDC_MSG_KEYPAD_LIMIT            1141
#define IDC_MSG_KEYPAD_TITLE            1142
#define IDC_MSG_LDPORT_ECSERVER         1143
#define IDC_MSG_LOCK                    1144
#define IDC_MSG_LOT_END                 1145
#define IDC_MSG_M_MESSAGE               1146
#define IDC_MSG_MACHINE_POS             1147
#define IDC_MSG_MANUAL_RATE             1148
#define IDC_MSG_MENU                    1149
#define IDC_MSG_MESSAGE                 1150
#define IDC_MSG_MOT_X_POS               1151
#define IDC_MSG_NEW_VALUE               1152
#define IDC_MSG_OLD_VALUE               1153
#define IDC_MSG_OPERATION_FILE          1154
#define IDC_MSG_OPERATION_FILE_NAME     1155
#define IDC_MSG_P_INDEX_TIME_FRONT_RACK_1_L 1156
#define IDC_MSG_P_INDEX_TIME_FRONT_RACK_1_R 1157
#define IDC_MSG_P_INDEX_TIME_FRONT_RACK_2_L 1158
#define IDC_MSG_P_INDEX_TIME_FRONT_RACK_2_R 1159
#define IDC_MSG_P_INDEX_TIME_REAR_RACK_1_L 1160
#define IDC_MSG_P_INDEX_TIME_REAR_RACK_1_R 1161
#define IDC_MSG_P_INDEX_TIME_REAR_RACK_2_L 1162
#define IDC_MSG_P_INDEX_TIME_REAR_RACK_2_R 1163
#define IDC_MSG_PARTIAL                 1164
#define IDC_MSG_PASS_CHG                1165
#define IDC_MSG_PASS_CHK                1166
#define IDC_MSG_PORT_APCT               1167
#define IDC_MSG_PORT_BPC                1168
#define IDC_MSG_PORT_ECSERVER           1169
#define IDC_MSG_PORT_ECSERVER2          1170
#define IDC_MSG_LOT_DISPLAY_PORT_ECSERVER 1170
#define IDC_MSG_PORT_NEXT               1171
#define IDC_MSG_ALARM_PORT_ECSERVER     1171
#define IDC_MSG_PORT_NMACHINE           1172
#define IDC_MSG_RETRY_WAIT              1173
#define IDC_MSG_RUN                     1174
#define IDC_MSG_RUN_RATE                1175
#define IDC_MSG_RUN_TIME                1176
#define IDC_MSG_SAVING                  1177
#define IDC_MSG_SERVER_PORT_APCT        1178
#define IDC_MSG_SERVER_PORT_FMACHINE    1179
#define IDC_MSG_STATUS_INFO             1180
#define IDC_MSG_STOP                    1181
#define IDC_MSG_STOP_TIME               1182
#define IDC_MSG_TESTERIPADDRESS         1183
#define IDC_MSG_TESTERPORT              1184
#define IDC_MSG_TRAY_X                  1185
#define IDC_MSG_TRAY_Y                  1186
#define IDC_MSG_WRUN_TIME               1187
#define IDC_MSG_BOAT_X                  1187
#define IDC_MSG_DISTANCE                1187
#define IDC_PAD_EQUIP_ID                1188
#define IDC_MSG_BOAT_Y                  1188
#define IDC_MSG_BRIGHTNESS              1188
#define IDC_PAD_EQUIP_NO                1189
#define IDC_MSG_SHUTTER_TIME            1189
#define IDC_PAD_FTP_PATH                1190
#define IDC_MSG_CONTRAST                1190
#define IDC_PAD_EC_EQUIP_ID             1190
#define IDC_PICTURE_ABOUT               1191
#define IDC_MSG_CODE_LENGTH             1191
#define IDC_RADIO1                      1192
#define IDC_RADIO_XY_BUF_1              1192
#define IDC_RADIO_LD_CLAMP_ON           1192
#define IDC_RADIO_LOB_IN                1192
#define IDC_RADIO_SCRAP_INPUT           1192
#define IDC_RADIO_ULD_1_STACKER         1192
#define IDC_RDO_DESKTOPS                1192
#define IDC_RADIO2                      1193
#define IDC_RADIO_XY_BUF_2              1193
#define IDC_RADIO_LD_CLAMP_OFF          1193
#define IDC_RADIO_LOB_ARRIVAL           1193
#define IDC_RADIO_SCRAP_4200            1193
#define IDC_RADIO_ULD_2_STACKER         1193
#define IDC_RDO_MSTATA                  1193
#define IDC_RADIO_AIR_BLOW              1194
#define IDC_RADIO_XY_GOOD               1194
#define IDC_RADIO_LD_BOAT_POS_1         1194
#define IDC_RADIO_LOADER_IN             1194
#define IDC_RADIO_SCRAP_4201            1194
#define IDC_RADIO_ULD_3_STACKER         1194
#define IDC_RADIO_ALARM                 1195
#define IDC_RADIO_XY_STACKER_1          1195
#define IDC_RADIO_LD_BOAT_POS_2         1195
#define IDC_RADIO_LOAD_LOWER            1195
#define IDC_RADIO_SCRAP_4202            1195
#define IDC_RADIO_ALL                   1196
#define IDC_RADIO_XY_PICKER_1           1196
#define IDC_RADIO_ULD_BOAT_CHK          1196
#define IDC_RADIO_LOADER_UPPER          1196
#define IDC_RADIO_WORK                  1196
#define IDC_RADIO_SCRAP_4599            1196
#define IDC_RADIO_APCT_TYPE_ALONE       1197
#define IDC_RADIO_XY_STACKER_2          1197
#define IDC_RADIO_ULD_CLAMP_ON          1197
#define IDC_RADIO_EMPTY_IN              1197
#define IDC_RADIO_APCT_TYPE_FRONT       1198
#define IDC_RADIO_XY_STACKER_3          1198
#define IDC_RADIO_ULD_CLAMP_OFF         1198
#define IDC_RADIO_EMPTY_LOWER           1198
#define IDC_RADIO_APCT_TYPE_REAR        1199
#define IDC_RADIO_XY_STACKER_4          1199
#define IDC_RADIO_ULD_CLAMP_UP          1199
#define IDC_RADIO_EMPTY_UPPER           1199
#define IDC_RADIO_BARCODE               1200
#define IDC_RADIO_XY_PICKER_2           1200
#define IDC_RADIO_ULD_CLAMP_DOWN        1200
#define IDC_RADIO_STACKER_1_IN          1200
#define IDC_RADIO_BOARD                 1201
#define IDC_RADIO_XY_PICKER_3           1201
#define IDC_RADIO_BUF_1_BOAT_CHECK      1201
#define IDC_RADIO_LOB_FULL              1201
#define IDC_RADIO_BOARD_INFO            1202
#define IDC_RADIO_XY_PICKER_4           1202
#define IDC_RADIO_BUF_1_CLAMP_CHECK     1202
#define IDC_RADIO_LOB_LATCH             1202
#define IDC_RADIO_CNT_1                 1203
#define IDC_RADIO_SAFETY_X              1203
#define IDC_RADIO_BUF_1_UNCLAMP_CHECK   1203
#define IDC_RADIO_STACKER_2_IN          1203
#define IDC_RADIO_CNT_10                1204
#define IDC_RADIO_XY_PICKER_R_0         1204
#define IDC_RADIO_BUF_1_ROTATOR_CHECK   1204
#define IDC_RADIO_STACKER_3_IN          1204
#define IDC_RADIO_CNT_100               1205
#define IDC_RADIO_SAFETY_YMD            1205
#define IDC_RADIO_BUF_2_BOAT_CHECK      1205
#define IDC_RADIO_MSTACKER_1_TRAY       1205
#define IDC_RADIO_CNT_50                1206
#define IDC_RADIO_SAFETY_YPD            1206
#define IDC_RADIO_BUF_2_CLAMP_CHECK     1206
#define IDC_RADIO_MSTACKER_2_TRAY       1206
#define IDC_RADIO_COUNT_INFO            1207
#define IDC_RADIO_XY_PICKER_R_180       1207
#define IDC_RADIO_BUF_2_UNCLAMP_CHECK   1207
#define IDC_RADIO_MSTACKER_3_TRAY       1207
#define IDC_RADIO_DEVICE_INFO           1208
#define IDC_RADIO_XY_PICKER_1_UP        1208
#define IDC_RADIO_BUF_2_ROTATOR_CHECK   1208
#define IDC_RADIO_MSTACKER_SD           1208
#define IDC_RADIO_DEVICE_MODE_NOTUSE    1209
#define IDC_RADIO_XY_PICKER_1_DN        1209
#define IDC_RADIO_BOAT_ID_1             1209
#define IDC_RADIO_TT_PCB                1209
#define IDC_RADIO_DEVICE_MODE_USE       1210
#define IDC_RADIO_XY_PICKER_2_UP        1210
#define IDC_RADIO_BOAT_ID_2             1210
#define IDC_RADIO_PICKER_2_PCB          1210
#define IDC_RADIO_DEVICE_TYPE_NORMAL    1211
#define IDC_RADIO_XY_PICKER_2_DN        1211
#define IDC_RADIO_BOAT_ID_3             1211
#define IDC_RADIO_TURN_MODE_YES         1211
#define IDC_RADIO_PICKER_1_PCB          1211
#define IDC_RADIO_DEVICE_TYPE_VLPDIMM   1212
#define IDC_RADIO_XY_PICKER_3_UP        1212
#define IDC_RADIO_BOAT_ID_4             1212
#define IDC_RADIO_TURN_MODE_NO          1212
#define IDC_RADIO_GOOD_TRAY             1212
#define IDC_RADIO_FRONT_BUFFER          1213
#define IDC_RADIO_XY_PICKER_3_DN        1213
#define IDC_RADIO_BOAT_ID_5             1213
#define IDC_RADIO_REVERSE_MODE_YES      1213
#define IDC_RADIO_GOOD_FULL             1213
#define IDC_RADIO_FRONT_SHIFTER         1214
#define IDC_RADIO_XY_PICKER_4_UP        1214
#define IDC_RADIO_BOAT_ID_6             1214
#define IDC_RADIO_REVERSE_MODE_NO       1214
#define IDC_RADIO_EMPTY_TRAY            1214
#define IDC_RADIO_FTP_MODE              1215
#define IDC_RADIO_XY_PICKER_4_DN        1215
#define IDC_RADIO_BOAT_ID_7             1215
#define IDC_RADIO_PICKER_TURN_MODE_YES  1215
#define IDC_RADIO_EMPTY_FULL            1215
#define IDC_RADIO_INTERFACE             1216
#define IDC_RADIO_XY_GRIPPER_UP         1216
#define IDC_RADIO_BOAT_ID_8             1216
#define IDC_RADIO_PICKER_TURN_MODE_NO   1216
#define IDC_RADIO_IO_BD                 1217
#define IDC_RADIO_XY_GRIPPER_DN         1217
#define IDC_RADIO_BOAT_CHK_1            1217
#define IDC_RADIO_PICKER_MODE_PICKER    1217
#define IDC_RADIO_STACKER_1_TRAY        1217
#define IDC_RADIO_PICKER_USE_MODE_1     1217
#define IDC_RADIO_IO_CNT_1              1218
#define IDC_RADIO_XY_PICKER_VACUUM_1    1218
#define IDC_RADIO_BOAT_CHK_2            1218
#define IDC_RADIO_PICKER_MODE_GRIPPER   1218
#define IDC_RADIO_STACKER_1_FULL        1218
#define IDC_RADIO_PICKER_USE_MODE_2     1218
#define IDC_RADIO_IO_CNT_10             1219
#define IDC_RADIO_XY_PICKER_VACUUM_2    1219
#define IDC_RADIO_WARPAGE_CHK           1219
#define IDC_RADIO_STACKER_1_LATCH       1219
#define IDC_RADIO_BCR_BACKGROUND_WHITE  1219
#define IDC_RADIO_IO_CNT_100            1220
#define IDC_RADIO_XY_PICKER_VACUUM_3    1220
#define IDC_RADIO_STACKER_2_TRAY        1220
#define IDC_RADIO_BCR_BACKGROUND_BLACK  1220
#define IDC_RADIO_IO_CNT_50             1221
#define IDC_RADIO_XY_PICKER_VACUUM_4    1221
#define IDC_RADIO_STACKER_2_FULL        1221
#define IDC_RADIO_BCR_BACKGROUND_BOTH   1221
#define IDC_RADIO_LOCAL_MODE            1222
#define IDC_RADIO_XY_GRIPPER_DVC_CHK    1222
#define IDC_RADIO_STACKER_2_LATCH       1222
#define IDC_RADIO_LOT                   1223
#define IDC_RADIO_STACKER_3_TRAY        1223
#define IDC_RADIO_LOT_INFO              1224
#define IDC_RADIO_STACKER_3_FULL        1224
#define IDC_RADIO_MACHINE               1225
#define IDC_RADIO_STACKER_3_LATCH       1225
#define IDC_RADIO_MLCT_NOT_USE          1226
#define IDC_RADIO_MSTACKER_TRAY         1226
#define IDC_RADIO_MLCT_USE              1227
#define IDC_RADIO_MSTACKER_FULL         1227
#define IDC_RADIO_MOT_BD                1228
#define IDC_RADIO_OPERATION             1229
#define IDC_RADIO_PART                  1230
#define IDC_RADIO_PASS_NEW              1231
#define IDC_RADIO_PASS_OLD              1232
#define IDC_RADIO_PASS_VERIFY           1233
#define IDC_RADIO_POS_1                 1234
#define IDC_RADIO_POS_2                 1235
#define IDC_RADIO_POS_3                 1236
#define IDC_RADIO_POS_4                 1237
#define IDC_RADIO_REAR_BUFFER           1238
#define IDC_RADIO_REAR_SHIFTER          1239
#define IDC_RADIO_RETEST_CALL_USE       1240
#define IDC_RADIO_RETEST_NOTUSE         1241
#define IDC_RADIO_RETEST_USE            1242
#define IDC_RADIO_RETETST_CALL_NOT_USE  1243
#define IDC_RADIO_RUN_MODE_OFFLINE      1244
#define IDC_RADIO_RUN_MODE_ONLINE       1245
#define IDC_RADIO_SORT_ROBOT            1246
#define IDC_RADIO_TEST_RESULT           1247
#define IDC_RADIO_TEST_TIME             1248
#define IDC_RADIO_TRAY_SUPPLY           1249
#define IDC_RADIO_INIT_ROBOT            1249
#define IDC_RADIO_INIT_XYZROBOT         1249
#define IDC_RADIO_TRAY_TRANSFER         1250
#define IDC_RADIO_INIT_BIN_STACKER_1    1250
#define IDC_RADIO_INIT_BOX_CLAMP        1250
#define IDC_RADIO_TRAY_UNLOADER         1251
#define IDC_RADIO_INIT_EMPTY_STACKER    1251
#define IDC_RADIO_INIT_LOADING_CONVEYOR 1251
#define IDC_RADIO_WITH_DVC              1252
#define IDC_RADIO_WITHOUT_DVC           1253
#define IDC_RADIO_INIT_GOOD_STACKER     1253
#define IDC_RADIO_WORK_MODE_BYPASS      1254
#define IDC_RADIO_INIT_LOB_BUFFER       1254
#define IDC_RADIO_WORK_MODE_WORK        1255
#define IDC_RADIO_INIT_MULTI_STACKER    1255
#define IDC_SELECT_MESSAGE              1256
#define IDC_RADIO_INIT_TRAY_TRANSFER    1256
#define IDC_START_DATE                  1257
#define IDC_RADIO_INIT_CONVEYOR         1257
#define IDC_START_TIME                  1258
#define IDC_RADIO_INIT_BIN_STACKER_2    1258
#define IDC_RADIO_INIT_BOX_LIFT         1258
#define IDC_STATIC_LAST_MODULE          1259
#define IDC_RADIO_INIT_BIN_STACKER_3    1259
#define IDC_RADIO_INIT_BUFFER_ALIGN_CONVEYOR 1259
#define IDC_STATIC_LOT_CHK              1260
#define IDC_TAB_MOTOR                   1261
#define IDC_TAB_MOTOR_PART              1262
#define IDC_TESTERIPADDRESS             1263
#define IDC_TITLE_BARCODE_MODE          1264
#define IDC_TITLE_DEVICE_MODE           1265
#define IDC_TITLE_FRONT_KEY             1266
#define IDC_TITLE_BCR_MODE              1266
#define IDC_TITLE_INTERFACE_MODE        1267
#define IDC_TITLE_CNNT_EQP2MAIN         1267
#define IDC_TITLE_LEVEL_MODE            1268
#define IDC_TITLE_PASS_CHK              1269
#define IDC_TITLE_REAR_KEY              1270
#define IDC_TITLE_RETEST_MODE           1271
#define IDC_TITLE_SOCKETOFF_MODE        1272
#define IDC_TITLE_MACHINE_MODE          1272
#define IDD_ABOUTBOX                    1273
#define IDD_DIALOG1                     1274
#define IDD_DIALOG_ABOUT                1275
#define IDD_DIALOG_ADD_FAIL             1276
#define IDD_DIALOG_ALARM                1277
#define IDD_DIALOG_BUFFER_STATUS        1278
#define IDD_DIALOG_COLOR                1279
#define IDD_DIALOG_EVENT_MSG            1280
#define IDD_DIALOG_EXIT                 1281
#define IDD_DIALOG_INFOR                1282
#define IDD_DIALOG_KEYBOARD             1283
#define IDD_DIALOG_KEYPAD               1284
#define IDD_DIALOG_LIST                 1285
#define IDD_DIALOG_MENU                 1286
#define IDD_DIALOG_MESSAGE              1287
#define IDD_DIALOG_MULTI_MSG            1288
#define IDD_DIALOG_PART_IO              1289
#define IDD_DIALOG_PART_MANUAL          1290
#define IDD_DIALOG_PASS_CHANGE          1291
#define IDD_DIALOG_PASS_CHECK           1292
#define IDD_DIALOG_SCRAP_INFO_VIEW      1293
#define IDD_DIALOG_SELECT               1294
#define IDD_DIALOG_TITLE                1295
#define IDD_DIALOG_TRACK_OUT            1296
#define IDD_HANDLER_FORM                1297
#define IDD_MOTOR_AXIS_1                1298
#define IDD_MOTOR_AXIS_10               1299
#define IDD_MOTOR_AXIS_2                1300
#define IDD_MOTOR_AXIS_3                1301
#define IDD_MOTOR_AXIS_4                1302
#define IDD_MOTOR_AXIS_5                1303
#define IDD_MOTOR_AXIS_6                1304
#define IDD_MOTOR_AXIS_7                1305
#define IDD_MOTOR_AXIS_8                1306
#define IDD_MOTOR_AXIS_9                1307
#define IDD_MOTOR_PART                  1308
#define IDD_SCREEN_ADMIN                1309
#define IDD_SCREEN_BASIC                1310
#define IDD_SCREEN_BASIC1               1311
#define IDD_SCREEN_DATA_VIEW            1312
#define IDD_SCREEN_FILE_EDITOR          1313
#define IDD_SCREEN_INITIAL              1314
#define IDD_SCREEN_IO                   1315
#define IDD_SCREEN_LIST_DATA_VIEW       1316
#define IDD_SCREEN_LIST_OPERATION       1317
#define IDD_SCREEN_LOCK                 1318
#define IDD_SCREEN_MAIN                 1319
#define IDD_SCREEN_MOTOR                1320
#define IDD_SCREEN_MOTOR_SPEED          1321
#define IDD_SCREEN_MOTOR_TEACH          1322
#define IDD_SCREEN_SET_INTERFACE        1323
#define IDD_SCREEN_SET_MAINTENANCE      1324
#define IDD_SCREEN_SET_TESTREFERENECE   1325
#define IDD_SCREEN_WAIT_TIME            1326
#define IDEXIT                          1327
#define IDR_MAINFRAME                   1328
#define IDI_EMG_STOP                    1329
#define IDI_EXIT                        1330
#define IDI_GRAY_LED_ICON               1331
#define IDI_GREEN_LED_ICON              1332
#define IDI_HOME                        1333
#define IDI_IO                          1334
#define IDI_KEYBOARD                    1335
#define IDI_LEFT                        1336
#define IDI_LIST_ARM                    1337
#define IDI_LIST_WORK                   1338
#define IDI_MAINTENANCE                 1339
#define IDI_MODULE                      1340
#define IDI_MOT_POS                     1341
#define IDI_MOT_SPD                     1342
#define IDI_MOTOR                       1343
#define IDI_N_DOWN                      1344
#define IDI_N_LEFT                      1345
#define IDI_N_RIGHT                     1346
#define IDI_N_UP                        1347
#define IDI_OPEN_FOLDER                 1348
#define IDI_RED_LED_ICON                1349
#define IDI_RIGHT                       1350
#define IDI_SOUND_OFF                   1351
#define IDI_SOUND_ON                    1352
#define IDI_TRAY                        1353
#define IDI_UP                          1354
#define IDP_SOCKETS_INIT_FAILED         1355
#define IDR_EMPTY                       1356
#define IDR_GIF_ALARM                   1357
#define IDR_GIF_CHOICE                  1358
#define IDR_GIF_EXIT                    1359
#define IDR_GIF_INITIALIZING            1360
#define IDR_GIF_LOCK                    1361
#define IDR_GIF_MENU                    1362
#define IDR_GIF_MSG                     1363
#define IDR_GIF_N_LOGO                  1364
#define IDR_HANDLETYPE                  1365
#define IDI_DN                          1366
#define IDSAVEOK                        1368
#define IDD_DIALOG_MANUAL_PART_1        1500
#define IDD_DIALOG_MANUAL_PART_2        1501
#define IDD_DIALOG_MANUAL_PART_3        1502
#define IDD_DIALOG_MANUAL_PART_4        1503
#define IDD_DIALOG_BARCODE_DATA         1504
#define IDC_CURSOR3                     1522
#define IDD_DIALOG_SMEMA                1523
#define IDD_DIALOG_NETWORK              1524
#define IDD_DIALOG_SETRESET             1525
#define IDC_EDIT_DC_NEW_NAME            1572
#define IDC_CHECK1                      1700
#define IDC_CHK_2_5_SSD                 1700
#define IDC_CHK_LOADING_STOP            1700
#define IDC_CHECK2                      1701
#define IDC_CHK_PICKER_1                1701
#define IDC_CHK_FORCEDISCHARGE          1701
#define IDC_CHECK3                      1702
#define IDC_CHK_PICKER_2                1702
#define IDC_CHK_ACCY_BCR_STATE1         1702
#define IDC_CHECK4                      1703
#define IDC_CHK_STACK_MODE              1703
#define IDC_CUSTOM2                     1704
#define IDC_CUSTOM_PLOT_INFO            1704
#define IDC_CHK_RFID_MODE               1704
#define IDC_BTN_LD_Z_PICK               1705
#define IDC_CHECK5                      1706
#define IDC_CHK_ACCY_BCR_STATE2         1706
#define IDC_CHECK6                      1707
#define IDC_CHK_ACCY_BCR_STATE3         1707
#define IDC_CHECK7                      1708
#define IDC_CHK_ACCY_BCR_STATE4         1708
#define IDC_CHECK8                      1709
#define IDC_CHK_NG_BUFFER_ACCY_1        1709
#define IDC_CHECK9                      1710
#define IDC_CHK_NG_BUFFER_ACCY_2        1710
#define IDC_CHECK10                     1711
#define IDC_CHK_NG_BUFFER_ACCY_3        1711
#define IDC_CHECK11                     1712
#define IDC_CHK_NG_BUFFER_ACCY_4        1712
#define IDC_CHECK12                     1713
#define IDC_BTN_LD_Z_PLACE_BUF_1        1714
#define IDC_BTN_LD_Z_PLACE_BUF_2        1715
#define IDC_BTN_LD_X_PICK               1716
#define IDC_BTN_LD_X_BUF_1              1717
#define IDC_BTN_LD_X_BUF_2              1718
#define IDC_BTN_LD_X_ID_CHECK           1719
#define IDC_BTN_LD_X_WP_1               1720
#define IDC_BTN_LD_M_BOAT_PICK          1721
#define IDC_BTN_LD_BOAT_CLAMP_ON        1722
#define IDC_BTN_LD_BOAT_CLAMP_OFF       1723
#define IDC_LABEL_ID_CHECK              1724
#define IDC_LABEL_BOAT_CHECK            1725
#define IDC_LABEL_WARPAGE_CHECK         1726
#define IDC_CHK_ID_1                    1727
#define IDC_CHK_ID_2                    1728
#define IDC_CHK_ID_3                    1729
#define IDC_CHK_ID_4                    1730
#define IDC_CHK_ID_5                    1731
#define IDC_CHK_ID_6                    1732
#define IDC_CHK_ID_7                    1733
#define IDC_CHK_ID_8                    1734
#define IDC_CHK_BOAT_1                  1735
#define IDC_CHK_BOAT_2                  1736
#define IDC_CHK_WARPAGE                 1737
#define IDC_BTN_ULD_UPDN_PLACE_DN       1738
#define IDC_BTN_ULD_UPDN_BUF_1_PICK_DN  1739
#define IDC_BTN_ULD_UPDN_BUF_2_PICK_DN  1740
#define IDC_BTN_ULD_X_PLACE             1741
#define IDC_BTN_ULD_X_BUF_1             1742
#define IDC_BTN_ULD_X_BUF_2             1743
#define IDC_BTN_ULD_BOAT_CLAMP_ON       1744
#define IDC_BTN_ULD_BOAT_CLAMP_OFF      1745
#define IDC_LABEL_ULD_BOAT_CHECK        1746
#define IDC_BTN_BUF1_BOAT_CLAMP         1746
#define IDC_CHK_ULD_BOAT                1747
#define IDC_BTN_BUF2_BOAT_CLAMP         1747
#define IDC_BTN_RBT_Z_SAFETY            1748
#define IDC_BTN_1_EXIT                  1748
#define IDC_BTN_LD_X_WP_2               1749
#define IDC_BTN_RBT_Z_BUF1_PICK         1749
#define IDC_BTN_LD_X_WP_3               1750
#define IDC_BTN_RBT_Z_BUF2_PICK         1750
#define IDC_BTN_LD_X_WP_4               1751
#define IDC_BTN_RBT_Z_BUF_PLACE         1751
#define IDC_BTN_LD_X_WP_5               1752
#define IDC_BTN_RBT_Z_FLIPPER_PICK      1752
#define IDC_BTN_LD_X_WP_6               1753
#define IDC_BTN_RBT_Z_FLIPPER_PLACE     1753
#define IDC_BTN_LD_X_WP_7               1754
#define IDC_BTN_RBT_Z_STACKER_PLACE     1754
#define IDC_BTN_LD_X_WP_8               1755
#define IDC_BTN_RBT_XY_GO               1755
#define IDC_BTN_ULD_X_BUF_3             1756
#define IDC_BTN_BUF1_LD                 1756
#define IDC_BTN_RBT_XY_SAFETY           1756
#define IDC_BTN_BUF1_FLIPPER            1757
#define IDC_BTN_RBT_XY_FLIPPER          1757
#define IDC_BTN_BUF1_ULD                1758
#define IDC_CMB_X                       1758
#define IDC_BTN_BUF1_DEG_0              1759
#define IDC_CMB_Y                       1759
#define IDC_BTN_BUF1_DEG_180            1760
#define IDC_MSG_CMB_X                   1760
#define IDC_BTN_BUF2_LD                 1761
#define IDC_MSG_CMB_Y                   1761
#define IDC_BTN_BUF2_FLIPPER            1762
#define IDC_BTN_RBT_VP_OPEN             1762
#define IDC_MSG_CMB_SITE                1762
#define IDC_BTN_BUF2_ULD                1763
#define IDC_BTN_RBT_VP_CLOSE            1763
#define IDC_CMB_SITE                    1763
#define IDC_BTN_BUF2_DEG_0              1764
#define IDC_BTN_RBT_GP_OPEN             1764
#define IDC_MSG_CMB_PICKER              1764
#define IDC_BTN_BUF2_DEG_180            1765
#define IDC_BTN_2_EXIT                  1765
#define IDC_CMB_PICKER                  1765
#define IDC_BTN_RBT_GP_CLOSE            1766
#define IDC_BTN_JIG_TURN_0              1766
#define IDC_BTN_LD_M_BOAT_PLACE_1       1766
#define IDC_MSG_CMB_MS_FLOOR            1766
#define IDC_BTN_JIG_TURN_90             1767
#define IDC_BTN_LD_M_BOAT_PLACE_2       1767
#define IDC_BTN_RBT_PICKER1_UP          1767
#define IDC_CMB_MS_FLOOR                1767
#define IDC_BTN_FLIPPER_Z_SAFETY        1768
#define IDC_BTN_ULD_M_BOAT_PLACE        1768
#define IDC_BTN_RBT_PICKER2_UP          1768
#define IDC_BTN_FLIPPER_Z_STATION_DOWN  1769
#define IDC_BTN_ULD_M_BOAT_PICK_1       1769
#define IDC_BTN_RBT_PICKER3_UP          1769
#define IDC_BTN_FLIPPER_SAFETY_GAP_DOWN 1770
#define IDC_BTN_RBT_PICKER4_UP          1770
#define IDC_BTN_BUF1_BOAT_CLAMP_OFF     1770
#define IDC_MSG_FLIPPER_Z               1771
#define IDC_BTN_ULD_M_BOAT_PICK_2       1771
#define IDC_BTN_RBT_GRIPPER_UP          1771
#define IDC_BTN_FLIPPER_Z_GO            1772
#define IDC_BTN_RBT_PICKER1_DN          1772
#define IDC_BTN_BUF2_BOAT_CLAMP_OFF     1772
#define IDC_BTN_FLIPPER_Y_SAFETY        1773
#define IDC_BTN_TT_Y_LOADER             1773
#define IDC_BTN_RBT_PICKER2_DN          1773
#define IDC_BTN_WARPAGE_SENSING         1773
#define IDC_BTN_FLIPPER_Y_STACKER       1774
#define IDC_BTN_TT_Y_STACKER_1          1774
#define IDC_BTN_RBT_PICKER3_DN          1774
#define IDC_BTN_FLIPPER_Y_Flipper       1775
#define IDC_BTN_TT_Y_STACKER_2          1775
#define IDC_BTN_RBT_PICKER4_DN          1775
#define IDC_BTN_TT_Y_STACKER_3          1776
#define IDC_BTN_3_EXIT                  1776
#define IDC_BTN_RBT_GRIPPER_DN          1776
#define IDC_BTN_TT_Y_STACKER_4          1777
#define IDC_BTN_RBT_PICKER_R_0          1777
#define IDC_BTN_FLIPPER_R_0             1777
#define IDC_BTN_TT_Y_GOOD               1778
#define IDC_BTN_RBT_PICKER_R_180        1778
#define IDC_BTN_FLIPPER_R_180           1778
#define IDC_BTN_TT_Z_SAFETY             1779
#define IDC_BTN_RBT_PICKER_VACCUM_1     1779
#define IDC_BTN_FLIPPER_TOP_CLAMP       1779
#define IDC_BTN_TT_Z_PICK               1780
#define IDC_BTN_RBT_PICKER_VACCUM_2     1780
#define IDC_BTN_FLIPPER_BOTTOM_CLAMP    1780
#define IDC_BTN_TT_Z_PLACE              1781
#define IDC_BTN_RBT_PICKER_VACCUM_3     1781
#define IDC_BTN_STAKCER_1_RECEIVE       1782
#define IDC_BTN_RBT_PICKER_VACCUM_4     1782
#define IDC_BTN_STAKCER_1_BASE          1783
#define IDC_BTN_RBT_PICKER_EJECTOR_1    1783
#define IDC_BTN_4_EXIT                  1784
#define IDC_BTN_RBT_PICKER_EJECTOR_2    1784
#define IDC_BTN_RBT_PICKER_EJECTOR_3    1785
#define IDC_RADIO_JIG_R_DVC_CHECK_1     1785
#define IDC_BTN_TT_FWDBWD               1785
#define IDC_BTN_RBT_PICKER_EJECTOR_4    1786
#define IDC_RADIO_JIG_R_DVC_CHECK_2     1786
#define IDC_RADIO_TT_FWD_CHK            1786
#define IDC_RADIO_JIG_R_POS_CHECK       1787
#define IDC_RADIO_TT_BWD_CHK            1787
#define IDC_RADIO_FM_L_SMEMA_TR_SIGNAL_CHK 1787
#define IDC_RADIO_FLIPPER_0_CHK         1788
#define IDC_BTN_TT_CLAMP                1788
#define IDC_BTN_FM_L_SMEMA_REQ_SIGNAL   1788
#define IDC_RADIO_FLIPPER_180_CHK       1789
#define IDC_RADIO_TT_CLAMP_CHK          1789
#define IDC_RADIO_FM_L_SMEMA_REQ_SIGNAL_CHK 1789
#define IDC_RADIO_FLIPPER_TOP_JIG_CLAMP 1790
#define IDC_RADIO_TT_UNCLAMP_CHK        1790
#define IDC_RADIO_FM_U_SMEMA_REQ_SIGNAL_CHK 1790
#define IDC_GROUP_SSD_AUTO_SORTER       1790
#define IDC_GROUP_SSD_FINAL_SORTER      1790
#define IDC_RADIO_FLIPPER_TOP_JIG_UNCLAMP 1791
#define IDC_BTN_CVY_STACKER_GUIDE1      1791
#define IDC_BTN_FM_U_SMEMA_TR_SIGNAL    1791
#define IDC_MSG_COMBINE_BIN_1           1791
#define IDC_RADIO_FLIPPER_BOTTOM_JIG_CLAMP 1792
#define IDC_RADIO_CVY_ST_GUIDE_ON_1     1792
#define IDC_RADIO_FM_U_SMEMA_TR_SIGNAL_CHK 1792
#define IDC_MSG_COMBINE_BIN_2           1792
#define IDC_RADIO_FLIPPER_BOTTOM_JIG_UNCLAMP 1793
#define IDC_RADIO_CVY_ST_GUIDE_OFF_1    1793
#define IDC_BTN_FM_L_SMEMA_REQ_SIGNAL_OFF 1793
#define IDC_MSG_COMBINE_BIN_4           1793
#define IDC_BTN_CVY_STACKER_GUIDE2      1794
#define IDC_MSG_COMBINE_BIN_8           1794
#define IDC_RADIO_CVY_ST_GUIDE_ON_2     1795
#define IDC_MSG_COMBINE_BIN_ASSEM       1795
#define IDC_MSG_COMBINE_BIN_CASE        1795
#define IDC_RADIO_CVY_ST_GUIDE_OFF_2    1796
#define IDC_BTN_FM_U_SMEMA_TR_SIGNAL_OFF 1796
#define IDC_MSG_COMBINE_BIN_SIZE        1796
#define IDC_MSG_COMBINE_BIN_ITESTER     1796
#define IDC_RADIO_STACKER_TRAY_CHK      1797
#define IDC_CMB_COMBINE_1               1797
#define IDC_BTN_CVY_STACKER_TRAY_PUSHER 1798
#define IDC_CMB_COMBINE_2               1798
#define IDC_RADIO_CVY_ST_TRAY_PUSHER_CHK 1799
#define IDC_CMB_COMBINE_4               1799
#define IDC_BTN_CVY_TRAY_STOPPER_UPDN   1800
#define IDC_CMB_COMBINE_8               1800
#define IDC_RADIO_CVY_STOPPER_UP_CHK    1801
#define IDC_CMB_COMBINE_ASSEM           1801
#define IDC_CMB_COMBINE_CASE            1801
#define IDC_RADIO_CVY_STOPPER_DN_CHK    1802
#define IDC_CMB_COMBINE_SIZE            1802
#define IDC_CMB_COMBINE_ITESTER         1802
#define IDC_RADIO_RAIL_IN_TRAY_CHK      1803
#define IDC_GROUP_BINCOMBINE            1803
#define IDC_BTN_STAKCER_1_RECEIVE_M     1804
#define IDC_MSG_COMBINE_BIN_UNKNOWN     1804
#define IDC_EDIT_WARPAGE_SENSING        1804
#define IDC_MSG_COMBINE_BIN_AVI         1804
#define IDC_MSG_COMBINE_BIN_ROUTER      1804
#define IDC_BTN_STAKCER_2_RECEIVE       1805
#define IDC_CMB_COMBINE_UNKNOWN         1805
#define IDC_CMB_COMBINE_AVI             1805
#define IDC_CMB_COMBINE_ROUTER          1805
#define IDC_BTN_STAKCER_2_BASE          1806
#define IDC_GROUP_BOAT_SETTING          1806
#define IDC_GROUP_PITCH                 1806
#define IDC_BTN_STAKCER_2_RECEIVE_M     1807
#define IDC_CUSTOM_BOAT_DATA            1807
#define IDC_BTN_STAKCER_3_RECEIVE       1808
#define IDC_LABEL_INSERT                1808
#define IDC_BTN_STAKCER_3_BASE          1809
#define IDC_LABEL_LOAD                  1809
#define IDC_BTN_STAKCER_3_RECEIVE_M     1810
#define IDC_LABEL_EMPTY                 1810
#define IDC_BTN_STAKCER_4_RECEIVE       1811
#define IDC_LABEL_ULD_1                 1811
#define IDC_BTN_STAKCER_4_BASE          1812
#define IDC_LABEL_ULD_2                 1812
#define IDC_BTN_STAKCER_4_RECEIVE_M     1813
#define IDC_LABEL_ULD_3                 1813
#define IDC_BTN_GOOD_S_SAFETY           1814
#define IDC_LABEL_MULTI                 1814
#define IDC_BTN_GOOD_S_RECIVE           1815
#define IDC_CUSTOM_PITCH                1815
#define IDC_BTN_GOOD_S_DOWN             1816
#define IDC_CUSTOM_LOB_LONG_UPDN        1816
#define IDC_BTN_CONVEYOR_SAFETY         1817
#define IDC_CUSTOM_LOB_SHORT_UPDN       1817
#define IDC_BTN_CONVEYOR_IN             1818
#define IDC_CUSTOM_LOB_LATCH_ONOFF      1818
#define IDC_BTN_CONVEYOR_OUT            1819
#define IDC_CUSTOM_LOB_STOPPER_UPDN     1819
#define IDC_RADIO_RAIL_OUT_TRAY_CHK     1820
#define IDC_RADIO_SAFETY_SENSOR_CHK_1   1821
#define IDC_GROUP_ROBOT_MOVE            1821
#define IDC_RADIO_SAFETY_SENSOR_CHK_2   1822
#define IDC_CUSTOM_LOAD_TRAY_UPDN       1822
#define IDC_RADIO_LIGHT_CURTAIN_CHK     1823
#define IDC_GROUP_TRAY_TRANSFER         1823
#define IDC_BTN_TRAY_PUSHER_1           1824
#define IDC_CUSTOM_LOAD_STOPPER_UPDN    1824
#define IDC_BTN_TRAY_PUSHER_2           1825
#define IDC_GROUP_ROBOT_PICKER          1825
#define IDC_BTN_TRAY_PUSHER_3           1826
#define IDC_GROUP_LOB_STACKER           1826
#define IDC_BTN_TRAY_PUSHER_4           1827
#define IDC_CUSTOM_EMPTY_TRAY_UPDN      1827
#define IDC_RADIO_PUSHER_ON_CHK_1       1828
#define IDC_GROUP_GOOD_STACKER          1828
#define IDC_BTN_TRAY_LD_STOPPER_UPDN    1829
#define IDC_CUSTOM_EMPTY_STOPPER_UPDN   1829
#define IDC_RADIO_TRAY_FULL_CHK_1       1830
#define IDC_GROUP_EMPTY_STACKER         1830
#define IDC_RADIO_TRAY_CHK_1            1831
#define IDC_GROUP_STACKER_1             1831
#define IDC_RADIO_TRAY_LOCK_CHK_1       1832
#define IDC_CUSTOM_STACKER_1_TRAY_UPDN  1832
#define IDC_RADIO_PUSHER_ON_CHK_2       1833
#define IDC_GROUP_STACKER_2             1833
#define IDC_RADIO_TRAY_FULL_CHK_2       1834
#define IDC_GROUP_STACKER_3             1834
#define IDC_RADIO_TRAY_CHK_2            1835
#define IDC_GROUP_MULTI_STACKER         1835
#define IDC_RADIO_TRAY_LOCK_CHK_2       1836
#define IDC_CUSTOM_STACKER_2_TRAY_UPDN  1836
#define IDC_RADIO_PUSHER_ON_CHK_3       1837
#define IDC_GROUP_MULTI_STACKER_MOVE    1837
#define IDC_RADIO_TRAY_FULL_CHK_3       1838
#define IDC_BTN_MENU_UNLOCK             1838
#define IDC_RADIO_TRAY_CHK_3            1839
#define IDC_EDIT_LOTID                  1839
#define IDC_CUSTOM_XGEM_INFO            1839
#define IDC_RADIO_TRAY_LOCK_CHK_3       1840
#define IDC_CUSTOM_STACKER_3_TRAY_UPDN  1840
#define IDC_BTN_LOTID_SET               1840
#define IDC_BUTTON_EQSTATUS             1840
#define IDC_RADIO_PUSHER_ON_CHK_4       1841
#define IDC_BTN_UPDATE                  1841
#define IDC_RADIO_TRAY_FULL_CHK_4       1842
#define IDC_CUSTOM_MSTACKER_PUSHER_ONOFF 1842
#define IDC_BTN_FILE_OPEN               1842
#define IDC_RADIO_TRAY_CHK_4            1843
#define IDC_CUSTOM_TT_UPDN              1843
#define IDC_RADIO_TRAY_LOCK_CHK_4       1844
#define IDC_CUSTOM_TT_PICKER_ONOFF      1844
#define IDC_CUSTOM_BCR_SELECT           1844
#define IDC_RADIO_TRAY_LD_UP_CHK        1845
#define IDC_CUSTOM_PICKER_ROTATE_ONOFF  1845
#define IDC_BTN_BASIC_ALL_CHECK         1845
#define IDC_RADIO_TRAY_LD_DN_CHK        1846
#define IDC_CUSTOM_PICKER_1_UPDN        1846
#define IDC_BTN_BASIC_CHECK_REMOVAL     1846
#define IDC_CUSTOM_PICKER_2_UPDN        1847
#define IDC_BTN_LOTEND                  1847
#define IDC_RADIO_TRAY_LD_TRAY_IN_CHK   1848
#define IDC_CUSTOM_PICKER_1_VACUUM      1848
#define IDC_GROUP_SMEMA_INFO            1848
#define IDC_RADIO_TRAY_LD_TRAY_OUT_CHK  1849
#define IDC_CUSTOM_PICKER_2_VACUUM      1849
#define IDC_BTN_BCR_TEST_ALL_CHECK      1849
#define IDC_GROUP_SMEMA_INFO2           1849
#define IDC_RADIO_TRAY_LD_SMEMA_TR_SIGNAL_CHK 1850
#define IDC_CUSTOM_PICKER_1_EJECTOR     1850
#define IDC_BTN_BCR_TEST_CHECK_REMOVAL  1850
#define IDC_BTN_TRAY_LOADER_SMEMA_REQUEST_SIGNAL 1851
#define IDC_CUSTOM_PICKER_2_EJECTOR     1851
#define IDC_DGT_WIDTH                   1851
#define IDC_BTN_FAIL                    1851
#define IDC_RADIO_R_MACHINE_SMEMA_REQUEST_SIGNAL_CHK 1852
#define IDC_MSG_WIDTH                   1852
#define IDC_BTN_REAR_MACHINE_SMEMA_TRANSFER_SIGNAL 1853
#define IDC_GROUP_BCR_BACKGROUND        1853
#define IDC_RADIO_R_MACHINE_SMEMA_TRANSFER_SIGNAL_CHK 1854
#define IDC_BTN_LAST_BUFFER_MANUAL      1854
#define IDC_RADIO_TRAY_LD_SMEMA_REQUEST_SIGNAL_CHK 1855
#define IDC_CUSTOM_ULD_STACKER_STATUS   1855
#define IDC_BTN_ALL_CHECK               1856
#define IDC_BTN_NEW_LOT_IN_RETRY        1856
#define IDC_CUSTOM_GOOD_LONG_UPDN       1857
#define IDC_BTN_BUFFER_IN_RETRY         1857
#define IDC_CUSTOM_GOOD_SHORT_UPDN      1858
#define IDC_CUSTOM_GOOD_LATCH_ONOFF     1859
#define IDC_GROUP_ULD_STACKER           1859
#define IDC_CUSTOM_GOOD_STOPPER_UPDN    1860
#define IDC_GROUP_TRAY_INFO             1860
#define IDC_CUSTOM_EMPTY_LONG_UPDN      1861
#define IDC_GROUP_ULD_STACKER_SELECT    1861
#define IDC_CUSTOM_EMPTY_SHORT_UPDN     1862
#define IDC_MSG_P_LOT_INFO              1862
#define IDC_CUSTOM_EMPTY_LATCH_ONOFF    1863
#define IDC_GROUP_P_LOT_INFO            1863
#define IDD_XGEMINTERFACE_DIALOG        1864
#define IDC_CUSTOM_STACKER_1_LIFTER_UPDN 1865
#define IDC_BUTTON18                    1865
#define IDC_CUSTOM_STACKER_2_LIFTER_UPDN 1866
#define IDC_EXGEMCTRL_GEM               1866
#define IDC_CUSTOM_STACKER_3_LIFTER_UPDN 1867
#define IDC_BTN_XGEM_TEST               1867
#define IDC_CUSTOM_MSTACKER_LIFTER_UPDN 1868
#define IDC_BTN_CONNECT_CIM             1868
#define IDC_EDIT_OPID                   1868
#define IDC_CUSTOM_LOAD_ALIGN_ONOFF     1869
#define IDC_BTN_DISCONNECT_CIM          1869
#define IDC_LABEL_OPID                  1869
#define IDC_CUSTOM_EMPTY_ALIGN_ONOFF    1870
#define IDC_BTN_CIM_START               1870
#define IDC_LABEL_WARNING               1870
#define IDC_CUSTOM_STACKER_1_ALIGN_ONOFF 1871
#define IDC_BTN_LOT_END                 1871
#define IDC_CUSTOM_STACKER_2_ALIGN_ONOFF 1872
#define IDC_BTN_FULLCARRIER_TEST        1872
#define IDC_CUSTOM_STACKER_3_ALIGN_ONOFF 1873
#define IDC_BTN_EMPTYCARRIER_TEST       1873
#define IDC_GROUP_SYSAUTO_TEST          1874
#define IDC_EDIT_SYSAUTO_LOTID          1875
#define IDC_GROUP_BASIC                 1876
#define IDC_GROUP_SET_DEVICE            1877
#define IDD_DIALOG_COPY                 1878
#define IDC_MSG_BCR_STATE               1878
#define IDC_MSG_BCR_STATE_1             1878
#define IDC_MSG_LOTEND_LDCV             1879
#define IDC_MSG_LOTEND_BOXCLAMP         1880
#define IDC_MSG_LOTEND_BOXLIFT          1881
#define IDC_MSG_LOTEND_XYZRBT           1882
#define IDC_MSG_LOTEND_BUFFCV           1883
#define IDC_GROUP_LOTEND                1884
#define IDC_MSG_LOADING_STATE           1885
#define IDC_GROUP_STATE                 1886
#define IDC_GROUP_BCR_STATE             1886
#define IDC_MSG_BCR_STATE_2             1887
#define IDC_MSG_BCR_STATE_3             1888
#define IDC_MSG_BCR_STATE_4             1889
#define IDC_MSG_BCR_DATA_1              1890
#define IDC_MSG_BCR_DATA_2              1891
#define IDC_MSG_BCR_DATA_3              1892
#define IDC_MSG_BCR_DATA_4              1893
#define IDC_GROUP_DVCTYPE               1894
#define IDC_MSG_DVC_TYPE                1894
#define IDC_GROUP_LOADING_STATE         1895
#define IDC_GROUP_DVC_TYPE              1896
#define IDC_MSG_FORCEDISCHARGE_STATE    1897
#define IDC_GROUP_FORCE_DISACHARGE_STATE 1898
#define IDC_LABEL_TIME_RUN              1906
#define IDC_BMP_ACCY_BOX_3              1908
#define IDC_BMP_ACCY_BOX_2              1909
#define IDC_BMP_ACCY_BOX_1              1910
#define IDC_LABEL_TIME_STOP             1911
#define IDC_LABEL_TIME_ALARM            1912
#define IDC_LABEL_TIME_MTBI             1913
#define IDC_DGT_TIME_RUN                1914
#define IDC_DGT_TIME_STOP               1915
#define IDC_DGT_TIME_ALARM              1916
#define IDC_DGT_TIME_MTBI               1917
#define IDC_BMP_CLAMP_ACCY_BOX_ACCY1    1918
#define IDC_BMP_NG_ACCY_OUT             1919
#define IDC_BMP_NG_BUFFER_ACCY_1        1920
#define IDC_BMP_EMTYP_ACCY_BOX_1        1921
#define IDC_BMP_EMTYP_ACCY_BOX_2        1922
#define IDC_BMP_NG_BUFFER_ACCY_2        1923
#define IDC_BMP_NG_BUFFER_ACCY_3        1924
#define IDC_BMP_NG_BUFFER_ACCY_4        1925
#define IDC_BMP_BUFFER_CONV_ACCY_1      1926
#define IDC_BMP_BUFFER_CONV_ACCY_2      1927
#define IDC_BMP_BUFFER_CONV_ACCY_3      1928
#define IDC_BMP_BUFFER_CONV_ACCY_4      1929
#define IDC_BMP_EMTYP_ACCY_BOX_3        1930
#define IDC_BMP_CLAMP_ACCY_BOX_ACCY2    1931
#define IDC_BMP_CLAMP_ACCY_BOX_ACCY3    1932
#define IDC_BMP_CLAMP_ACCY_BOX_ACCY     1932
#define IDC_BMP_CLAMP_ACCY_BOX_ACCY4    1933
#define IDC_BMP_CLAMP_ACCY_BOX_ACCY5    1934
#define IDC_BMP_CLAMP_ACCY_BOX_ACCY6    1935
#define IDC_BMP_CLAMP_ACCY_BOX_ACCY7    1936
#define IDC_BMP_CLAMP_ACCY_BOX_ACCY8    1937
#define IDC_CUSTOM_REQ_INFO             1938
#define IDC_BUTTON_NETWORK              1939
#define IDC_BUTTON_SMEMA                1940
#define IDC_BTN_NETWORK_ADDR_LOAD       1941
#define IDC_BTN_NETWORK_ADDR_MODIFY     1942
#define IDC_GROUP_EQP_STATE             1943
#define IDC_GROUP_GRIPPER_INFO          1944
#define IDC_BUTTON_REALIGN              1945
#define IDC_BUTTON_SET                  1946
#define IDC_BTN_BCR_READ_TEST           1946
#define IDC_BUTTON_RESET                1947
#define IDC_LBL_MAT_CODE                1947
#define IDC_GROUP_VARIABLE              1948
#define IDC_CHK_SLOP_VARIABLE           1949
#define IDC_MSG_DC_ORG_NAME             2300

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        1528
#define _APS_NEXT_COMMAND_VALUE         1600
#define _APS_NEXT_CONTROL_VALUE         1950
#define _APS_NEXT_SYMED_VALUE           1881
#endif
#endif
